// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

// Package upf contains generated bindings for API file upf.api.
//
// Contents:
// -  3 enums
// - 68 messages
package upf

import (
	"strconv"

	interface_types "github.com/travelping/upg-vpp/test/e2e/binapi/interface_types"
	ip_types "github.com/travelping/upg-vpp/test/e2e/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "upf"
	APIVersion = "2.0.0"
	VersionCrc = 0x72261e75
)

// UpfIpfixRecordFlags defines enum 'upf_ipfix_record_flags'.
type UpfIpfixRecordFlags uint8

const (
	UPF_IPFIX_RECORD_FLAG_L3 UpfIpfixRecordFlags = 1
	UPF_IPFIX_RECORD_FLAG_L4 UpfIpfixRecordFlags = 2
)

var (
	UpfIpfixRecordFlags_name = map[uint8]string{
		1: "UPF_IPFIX_RECORD_FLAG_L3",
		2: "UPF_IPFIX_RECORD_FLAG_L4",
	}
	UpfIpfixRecordFlags_value = map[string]uint8{
		"UPF_IPFIX_RECORD_FLAG_L3": 1,
		"UPF_IPFIX_RECORD_FLAG_L4": 2,
	}
)

func (x UpfIpfixRecordFlags) String() string {
	s, ok := UpfIpfixRecordFlags_name[uint8(x)]
	if ok {
		return s
	}
	str := func(n uint8) string {
		s, ok := UpfIpfixRecordFlags_name[uint8(n)]
		if ok {
			return s
		}
		return "UpfIpfixRecordFlags(" + strconv.Itoa(int(n)) + ")"
	}
	for i := uint8(0); i <= 8; i++ {
		val := uint8(x)
		if val&(1<<i) != 0 {
			if s != "" {
				s += "|"
			}
			s += str(1 << i)
		}
	}
	if s == "" {
		return str(uint8(x))
	}
	return s
}

// UpfIpfixWhichFlags defines enum 'upf_ipfix_which_flags'.
type UpfIpfixWhichFlags uint8

const (
	UPF_IPFIX_WHICH_FLAG_IP4 UpfIpfixWhichFlags = 1
	UPF_IPFIX_WHICH_FLAG_IP6 UpfIpfixWhichFlags = 2
)

var (
	UpfIpfixWhichFlags_name = map[uint8]string{
		1: "UPF_IPFIX_WHICH_FLAG_IP4",
		2: "UPF_IPFIX_WHICH_FLAG_IP6",
	}
	UpfIpfixWhichFlags_value = map[string]uint8{
		"UPF_IPFIX_WHICH_FLAG_IP4": 1,
		"UPF_IPFIX_WHICH_FLAG_IP6": 2,
	}
)

func (x UpfIpfixWhichFlags) String() string {
	s, ok := UpfIpfixWhichFlags_name[uint8(x)]
	if ok {
		return s
	}
	str := func(n uint8) string {
		s, ok := UpfIpfixWhichFlags_name[uint8(n)]
		if ok {
			return s
		}
		return "UpfIpfixWhichFlags(" + strconv.Itoa(int(n)) + ")"
	}
	for i := uint8(0); i <= 8; i++ {
		val := uint8(x)
		if val&(1<<i) != 0 {
			if s != "" {
				s += "|"
			}
			s += str(1 << i)
		}
	}
	if s == "" {
		return str(uint8(x))
	}
	return s
}

// UpfNodeIDType defines enum 'upf_node_id_type'.
type UpfNodeIDType uint8

const (
	UPF_NODE_TYPE_IPv4 UpfNodeIDType = 0
	UPF_NODE_TYPE_IPv6 UpfNodeIDType = 1
	UPF_NODE_TYPE_FQDN UpfNodeIDType = 2
)

var (
	UpfNodeIDType_name = map[uint8]string{
		0: "UPF_NODE_TYPE_IPv4",
		1: "UPF_NODE_TYPE_IPv6",
		2: "UPF_NODE_TYPE_FQDN",
	}
	UpfNodeIDType_value = map[string]uint8{
		"UPF_NODE_TYPE_IPv4": 0,
		"UPF_NODE_TYPE_IPv6": 1,
		"UPF_NODE_TYPE_FQDN": 2,
	}
)

func (x UpfNodeIDType) String() string {
	s, ok := UpfNodeIDType_name[uint8(x)]
	if ok {
		return s
	}
	return "UpfNodeIDType(" + strconv.Itoa(int(x)) + ")"
}

// AdfActiveVersionDetails defines message 'adf_active_version_details'.
type AdfActiveVersionDetails struct {
	IsRegex bool   `binapi:"bool,name=is_regex" json:"is_regex,omitempty"`
	Rule    []byte `binapi:"u8[1024],name=rule" json:"rule,omitempty"`
}

func (m *AdfActiveVersionDetails) Reset()               { *m = AdfActiveVersionDetails{} }
func (*AdfActiveVersionDetails) GetMessageName() string { return "adf_active_version_details" }
func (*AdfActiveVersionDetails) GetCrcString() string   { return "85a4f8a6" }
func (*AdfActiveVersionDetails) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfActiveVersionDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1        // m.IsRegex
	size += 1 * 1024 // m.Rule
	return size
}
func (m *AdfActiveVersionDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsRegex)
	buf.EncodeBytes(m.Rule, 1024)
	return buf.Bytes(), nil
}
func (m *AdfActiveVersionDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsRegex = buf.DecodeBool()
	m.Rule = make([]byte, 1024)
	copy(m.Rule, buf.DecodeBytes(len(m.Rule)))
	return nil
}

// AdfActiveVersionDump defines message 'adf_active_version_dump'.
type AdfActiveVersionDump struct {
	AppName []byte `binapi:"u8[64],name=app_name" json:"app_name,omitempty"`
}

func (m *AdfActiveVersionDump) Reset()               { *m = AdfActiveVersionDump{} }
func (*AdfActiveVersionDump) GetMessageName() string { return "adf_active_version_dump" }
func (*AdfActiveVersionDump) GetCrcString() string   { return "396ae46d" }
func (*AdfActiveVersionDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfActiveVersionDump) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.AppName
	return size
}
func (m *AdfActiveVersionDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.AppName, 64)
	return buf.Bytes(), nil
}
func (m *AdfActiveVersionDump) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AppName = make([]byte, 64)
	copy(m.AppName, buf.DecodeBytes(len(m.AppName)))
	return nil
}

// AdfAddIPRule defines message 'adf_add_ip_rule'.
type AdfAddIPRule struct {
	AppName []byte `binapi:"u8[64],name=app_name" json:"app_name,omitempty"`
	Rule    []byte `binapi:"u8[1024],name=rule" json:"rule,omitempty"`
}

func (m *AdfAddIPRule) Reset()               { *m = AdfAddIPRule{} }
func (*AdfAddIPRule) GetMessageName() string { return "adf_add_ip_rule" }
func (*AdfAddIPRule) GetCrcString() string   { return "63c56102" }
func (*AdfAddIPRule) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfAddIPRule) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64   // m.AppName
	size += 1 * 1024 // m.Rule
	return size
}
func (m *AdfAddIPRule) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.AppName, 64)
	buf.EncodeBytes(m.Rule, 1024)
	return buf.Bytes(), nil
}
func (m *AdfAddIPRule) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AppName = make([]byte, 64)
	copy(m.AppName, buf.DecodeBytes(len(m.AppName)))
	m.Rule = make([]byte, 1024)
	copy(m.Rule, buf.DecodeBytes(len(m.Rule)))
	return nil
}

// AdfAddIPRuleReply defines message 'adf_add_ip_rule_reply'.
type AdfAddIPRuleReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfAddIPRuleReply) Reset()               { *m = AdfAddIPRuleReply{} }
func (*AdfAddIPRuleReply) GetMessageName() string { return "adf_add_ip_rule_reply" }
func (*AdfAddIPRuleReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfAddIPRuleReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfAddIPRuleReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfAddIPRuleReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfAddIPRuleReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// AdfAddL7Rule defines message 'adf_add_l7_rule'.
type AdfAddL7Rule struct {
	AppName []byte `binapi:"u8[64],name=app_name" json:"app_name,omitempty"`
	Regex   []byte `binapi:"u8[1024],name=regex" json:"regex,omitempty"`
}

func (m *AdfAddL7Rule) Reset()               { *m = AdfAddL7Rule{} }
func (*AdfAddL7Rule) GetMessageName() string { return "adf_add_l7_rule" }
func (*AdfAddL7Rule) GetCrcString() string   { return "45034242" }
func (*AdfAddL7Rule) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfAddL7Rule) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64   // m.AppName
	size += 1 * 1024 // m.Regex
	return size
}
func (m *AdfAddL7Rule) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.AppName, 64)
	buf.EncodeBytes(m.Regex, 1024)
	return buf.Bytes(), nil
}
func (m *AdfAddL7Rule) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AppName = make([]byte, 64)
	copy(m.AppName, buf.DecodeBytes(len(m.AppName)))
	m.Regex = make([]byte, 1024)
	copy(m.Regex, buf.DecodeBytes(len(m.Regex)))
	return nil
}

// AdfAddL7RuleReply defines message 'adf_add_l7_rule_reply'.
type AdfAddL7RuleReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfAddL7RuleReply) Reset()               { *m = AdfAddL7RuleReply{} }
func (*AdfAddL7RuleReply) GetMessageName() string { return "adf_add_l7_rule_reply" }
func (*AdfAddL7RuleReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfAddL7RuleReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfAddL7RuleReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfAddL7RuleReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfAddL7RuleReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// AdfApplicationDetails defines message 'adf_application_details'.
type AdfApplicationDetails struct {
	Name  []byte `binapi:"u8[64],name=name" json:"name,omitempty"`
	Flags uint32 `binapi:"u32,name=flags" json:"flags,omitempty"`
}

func (m *AdfApplicationDetails) Reset()               { *m = AdfApplicationDetails{} }
func (*AdfApplicationDetails) GetMessageName() string { return "adf_application_details" }
func (*AdfApplicationDetails) GetCrcString() string   { return "0ef16c59" }
func (*AdfApplicationDetails) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfApplicationDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.Name
	size += 4      // m.Flags
	return size
}
func (m *AdfApplicationDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.Name, 64)
	buf.EncodeUint32(m.Flags)
	return buf.Bytes(), nil
}
func (m *AdfApplicationDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = make([]byte, 64)
	copy(m.Name, buf.DecodeBytes(len(m.Name)))
	m.Flags = buf.DecodeUint32()
	return nil
}

// AdfApplicationDump defines message 'adf_application_dump'.
type AdfApplicationDump struct{}

func (m *AdfApplicationDump) Reset()               { *m = AdfApplicationDump{} }
func (*AdfApplicationDump) GetMessageName() string { return "adf_application_dump" }
func (*AdfApplicationDump) GetCrcString() string   { return "51077d14" }
func (*AdfApplicationDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfApplicationDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *AdfApplicationDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *AdfApplicationDump) Unmarshal(b []byte) error {
	return nil
}

// AdfCreateApplication defines message 'adf_create_application'.
type AdfCreateApplication struct {
	Name  []byte `binapi:"u8[64],name=name" json:"name,omitempty"`
	Flags uint32 `binapi:"u32,name=flags" json:"flags,omitempty"`
}

func (m *AdfCreateApplication) Reset()               { *m = AdfCreateApplication{} }
func (*AdfCreateApplication) GetMessageName() string { return "adf_create_application" }
func (*AdfCreateApplication) GetCrcString() string   { return "0ef16c59" }
func (*AdfCreateApplication) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfCreateApplication) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.Name
	size += 4      // m.Flags
	return size
}
func (m *AdfCreateApplication) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.Name, 64)
	buf.EncodeUint32(m.Flags)
	return buf.Bytes(), nil
}
func (m *AdfCreateApplication) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = make([]byte, 64)
	copy(m.Name, buf.DecodeBytes(len(m.Name)))
	m.Flags = buf.DecodeUint32()
	return nil
}

// AdfCreateApplicationReply defines message 'adf_create_application_reply'.
type AdfCreateApplicationReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfCreateApplicationReply) Reset()               { *m = AdfCreateApplicationReply{} }
func (*AdfCreateApplicationReply) GetMessageName() string { return "adf_create_application_reply" }
func (*AdfCreateApplicationReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfCreateApplicationReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfCreateApplicationReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfCreateApplicationReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfCreateApplicationReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// AdfCreateVersion defines message 'adf_create_version'.
type AdfCreateVersion struct {
	AppName []byte `binapi:"u8[64],name=app_name" json:"app_name,omitempty"`
}

func (m *AdfCreateVersion) Reset()               { *m = AdfCreateVersion{} }
func (*AdfCreateVersion) GetMessageName() string { return "adf_create_version" }
func (*AdfCreateVersion) GetCrcString() string   { return "396ae46d" }
func (*AdfCreateVersion) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfCreateVersion) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.AppName
	return size
}
func (m *AdfCreateVersion) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.AppName, 64)
	return buf.Bytes(), nil
}
func (m *AdfCreateVersion) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AppName = make([]byte, 64)
	copy(m.AppName, buf.DecodeBytes(len(m.AppName)))
	return nil
}

// AdfCreateVersionReply defines message 'adf_create_version_reply'.
type AdfCreateVersionReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfCreateVersionReply) Reset()               { *m = AdfCreateVersionReply{} }
func (*AdfCreateVersionReply) GetMessageName() string { return "adf_create_version_reply" }
func (*AdfCreateVersionReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfCreateVersionReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfCreateVersionReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfCreateVersionReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfCreateVersionReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// AdfDeleteApplication defines message 'adf_delete_application'.
type AdfDeleteApplication struct {
	Name []byte `binapi:"u8[64],name=name" json:"name,omitempty"`
}

func (m *AdfDeleteApplication) Reset()               { *m = AdfDeleteApplication{} }
func (*AdfDeleteApplication) GetMessageName() string { return "adf_delete_application" }
func (*AdfDeleteApplication) GetCrcString() string   { return "0cb71b0e" }
func (*AdfDeleteApplication) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfDeleteApplication) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.Name
	return size
}
func (m *AdfDeleteApplication) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.Name, 64)
	return buf.Bytes(), nil
}
func (m *AdfDeleteApplication) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = make([]byte, 64)
	copy(m.Name, buf.DecodeBytes(len(m.Name)))
	return nil
}

// AdfDeleteApplicationReply defines message 'adf_delete_application_reply'.
type AdfDeleteApplicationReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfDeleteApplicationReply) Reset()               { *m = AdfDeleteApplicationReply{} }
func (*AdfDeleteApplicationReply) GetMessageName() string { return "adf_delete_application_reply" }
func (*AdfDeleteApplicationReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfDeleteApplicationReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfDeleteApplicationReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfDeleteApplicationReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfDeleteApplicationReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// AdfVersionCommit defines message 'adf_version_commit'.
type AdfVersionCommit struct {
	AppName []byte `binapi:"u8[64],name=app_name" json:"app_name,omitempty"`
}

func (m *AdfVersionCommit) Reset()               { *m = AdfVersionCommit{} }
func (*AdfVersionCommit) GetMessageName() string { return "adf_version_commit" }
func (*AdfVersionCommit) GetCrcString() string   { return "396ae46d" }
func (*AdfVersionCommit) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfVersionCommit) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.AppName
	return size
}
func (m *AdfVersionCommit) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.AppName, 64)
	return buf.Bytes(), nil
}
func (m *AdfVersionCommit) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AppName = make([]byte, 64)
	copy(m.AppName, buf.DecodeBytes(len(m.AppName)))
	return nil
}

// AdfVersionCommitReply defines message 'adf_version_commit_reply'.
type AdfVersionCommitReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfVersionCommitReply) Reset()               { *m = AdfVersionCommitReply{} }
func (*AdfVersionCommitReply) GetMessageName() string { return "adf_version_commit_reply" }
func (*AdfVersionCommitReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfVersionCommitReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfVersionCommitReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfVersionCommitReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfVersionCommitReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// AdfVersionDrop defines message 'adf_version_drop'.
type AdfVersionDrop struct {
	AppName []byte `binapi:"u8[64],name=app_name" json:"app_name,omitempty"`
}

func (m *AdfVersionDrop) Reset()               { *m = AdfVersionDrop{} }
func (*AdfVersionDrop) GetMessageName() string { return "adf_version_drop" }
func (*AdfVersionDrop) GetCrcString() string   { return "396ae46d" }
func (*AdfVersionDrop) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *AdfVersionDrop) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64 // m.AppName
	return size
}
func (m *AdfVersionDrop) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.AppName, 64)
	return buf.Bytes(), nil
}
func (m *AdfVersionDrop) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.AppName = make([]byte, 64)
	copy(m.AppName, buf.DecodeBytes(len(m.AppName)))
	return nil
}

// AdfVersionDropReply defines message 'adf_version_drop_reply'.
type AdfVersionDropReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AdfVersionDropReply) Reset()               { *m = AdfVersionDropReply{} }
func (*AdfVersionDropReply) GetMessageName() string { return "adf_version_drop_reply" }
func (*AdfVersionDropReply) GetCrcString() string   { return "e8d4e804" }
func (*AdfVersionDropReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *AdfVersionDropReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *AdfVersionDropReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *AdfVersionDropReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// NetcapImsiDetails defines message 'netcap_imsi_details'.
type NetcapImsiDetails struct {
	Imsi           []byte `binapi:"u8[8],name=imsi" json:"imsi,omitempty"`
	TargetLen      uint8  `binapi:"u8,name=target_len" json:"target_len,omitempty"`
	Target         []byte `binapi:"u8[64],name=target" json:"target,omitempty"`
	TagLen         uint8  `binapi:"u8,name=tag_len" json:"tag_len,omitempty"`
	Tag            []byte `binapi:"u8[64],name=tag" json:"tag,omitempty"`
	PacketMaxBytes uint16 `binapi:"u16,name=packet_max_bytes" json:"packet_max_bytes,omitempty"`
}

func (m *NetcapImsiDetails) Reset()               { *m = NetcapImsiDetails{} }
func (*NetcapImsiDetails) GetMessageName() string { return "netcap_imsi_details" }
func (*NetcapImsiDetails) GetCrcString() string   { return "e002db45" }
func (*NetcapImsiDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *NetcapImsiDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 8  // m.Imsi
	size += 1      // m.TargetLen
	size += 1 * 64 // m.Target
	size += 1      // m.TagLen
	size += 1 * 64 // m.Tag
	size += 2      // m.PacketMaxBytes
	return size
}
func (m *NetcapImsiDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.Imsi, 8)
	buf.EncodeUint8(m.TargetLen)
	buf.EncodeBytes(m.Target, 64)
	buf.EncodeUint8(m.TagLen)
	buf.EncodeBytes(m.Tag, 64)
	buf.EncodeUint16(m.PacketMaxBytes)
	return buf.Bytes(), nil
}
func (m *NetcapImsiDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Imsi = make([]byte, 8)
	copy(m.Imsi, buf.DecodeBytes(len(m.Imsi)))
	m.TargetLen = buf.DecodeUint8()
	m.Target = make([]byte, 64)
	copy(m.Target, buf.DecodeBytes(len(m.Target)))
	m.TagLen = buf.DecodeUint8()
	m.Tag = make([]byte, 64)
	copy(m.Tag, buf.DecodeBytes(len(m.Tag)))
	m.PacketMaxBytes = buf.DecodeUint16()
	return nil
}

// NetcapImsiDump defines message 'netcap_imsi_dump'.
type NetcapImsiDump struct{}

func (m *NetcapImsiDump) Reset()               { *m = NetcapImsiDump{} }
func (*NetcapImsiDump) GetMessageName() string { return "netcap_imsi_dump" }
func (*NetcapImsiDump) GetCrcString() string   { return "51077d14" }
func (*NetcapImsiDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *NetcapImsiDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *NetcapImsiDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *NetcapImsiDump) Unmarshal(b []byte) error {
	return nil
}

// UpfGetNodeID defines message 'upf_get_node_id'.
type UpfGetNodeID struct{}

func (m *UpfGetNodeID) Reset()               { *m = UpfGetNodeID{} }
func (*UpfGetNodeID) GetMessageName() string { return "upf_get_node_id" }
func (*UpfGetNodeID) GetCrcString() string   { return "51077d14" }
func (*UpfGetNodeID) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfGetNodeID) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfGetNodeID) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfGetNodeID) Unmarshal(b []byte) error {
	return nil
}

// UpfGetNodeIDReply defines message 'upf_get_node_id_reply'.
type UpfGetNodeIDReply struct {
	Retval  int32            `binapi:"i32,name=retval" json:"retval,omitempty"`
	Type    uint8            `binapi:"u8,name=type" json:"type,omitempty"`
	IP      ip_types.Address `binapi:"address,name=ip" json:"ip,omitempty"`
	FqdnLen uint8            `binapi:"u8,name=fqdn_len" json:"-"`
	Fqdn    []byte           `binapi:"u8[fqdn_len],name=fqdn" json:"fqdn,omitempty"`
}

func (m *UpfGetNodeIDReply) Reset()               { *m = UpfGetNodeIDReply{} }
func (*UpfGetNodeIDReply) GetMessageName() string { return "upf_get_node_id_reply" }
func (*UpfGetNodeIDReply) GetCrcString() string   { return "4f226741" }
func (*UpfGetNodeIDReply) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfGetNodeIDReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4               // m.Retval
	size += 1               // m.Type
	size += 1               // m.IP.Af
	size += 1 * 16          // m.IP.Un
	size += 1               // m.FqdnLen
	size += 1 * len(m.Fqdn) // m.Fqdn
	return size
}
func (m *UpfGetNodeIDReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint8(m.Type)
	buf.EncodeUint8(uint8(m.IP.Af))
	buf.EncodeBytes(m.IP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(len(m.Fqdn)))
	buf.EncodeBytes(m.Fqdn, 0)
	return buf.Bytes(), nil
}
func (m *UpfGetNodeIDReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.Type = buf.DecodeUint8()
	m.IP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.IP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.FqdnLen = buf.DecodeUint8()
	m.Fqdn = make([]byte, m.FqdnLen)
	copy(m.Fqdn, buf.DecodeBytes(len(m.Fqdn)))
	return nil
}

// UpfImsiNetcapEnableDisable defines message 'upf_imsi_netcap_enable_disable'.
type UpfImsiNetcapEnableDisable struct {
	Imsi           []byte `binapi:"u8[8],name=imsi" json:"imsi,omitempty"`
	TargetLen      uint8  `binapi:"u8,name=target_len" json:"target_len,omitempty"`
	Target         []byte `binapi:"u8[64],name=target" json:"target,omitempty"`
	TagLen         uint8  `binapi:"u8,name=tag_len" json:"tag_len,omitempty"`
	Tag            []byte `binapi:"u8[64],name=tag" json:"tag,omitempty"`
	PacketMaxBytes uint16 `binapi:"u16,name=packet_max_bytes" json:"packet_max_bytes,omitempty"`
	IsEnable       bool   `binapi:"bool,name=is_enable" json:"is_enable,omitempty"`
}

func (m *UpfImsiNetcapEnableDisable) Reset()               { *m = UpfImsiNetcapEnableDisable{} }
func (*UpfImsiNetcapEnableDisable) GetMessageName() string { return "upf_imsi_netcap_enable_disable" }
func (*UpfImsiNetcapEnableDisable) GetCrcString() string   { return "4d8ef09f" }
func (*UpfImsiNetcapEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfImsiNetcapEnableDisable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 8  // m.Imsi
	size += 1      // m.TargetLen
	size += 1 * 64 // m.Target
	size += 1      // m.TagLen
	size += 1 * 64 // m.Tag
	size += 2      // m.PacketMaxBytes
	size += 1      // m.IsEnable
	return size
}
func (m *UpfImsiNetcapEnableDisable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.Imsi, 8)
	buf.EncodeUint8(m.TargetLen)
	buf.EncodeBytes(m.Target, 64)
	buf.EncodeUint8(m.TagLen)
	buf.EncodeBytes(m.Tag, 64)
	buf.EncodeUint16(m.PacketMaxBytes)
	buf.EncodeBool(m.IsEnable)
	return buf.Bytes(), nil
}
func (m *UpfImsiNetcapEnableDisable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Imsi = make([]byte, 8)
	copy(m.Imsi, buf.DecodeBytes(len(m.Imsi)))
	m.TargetLen = buf.DecodeUint8()
	m.Target = make([]byte, 64)
	copy(m.Target, buf.DecodeBytes(len(m.Target)))
	m.TagLen = buf.DecodeUint8()
	m.Tag = make([]byte, 64)
	copy(m.Tag, buf.DecodeBytes(len(m.Tag)))
	m.PacketMaxBytes = buf.DecodeUint16()
	m.IsEnable = buf.DecodeBool()
	return nil
}

// UpfImsiNetcapEnableDisableReply defines message 'upf_imsi_netcap_enable_disable_reply'.
type UpfImsiNetcapEnableDisableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfImsiNetcapEnableDisableReply) Reset() { *m = UpfImsiNetcapEnableDisableReply{} }
func (*UpfImsiNetcapEnableDisableReply) GetMessageName() string {
	return "upf_imsi_netcap_enable_disable_reply"
}
func (*UpfImsiNetcapEnableDisableReply) GetCrcString() string { return "e8d4e804" }
func (*UpfImsiNetcapEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfImsiNetcapEnableDisableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfImsiNetcapEnableDisableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfImsiNetcapEnableDisableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfNatPoolAdd defines message 'upf_nat_pool_add'.
type UpfNatPoolAdd struct {
	IsAdd     bool                `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	MinPort   uint16              `binapi:"u16,name=min_port" json:"min_port,omitempty"`
	MaxPort   uint16              `binapi:"u16,name=max_port" json:"max_port,omitempty"`
	BlockSize uint32              `binapi:"u32,name=block_size" json:"block_size,omitempty"`
	Start     ip_types.IP4Address `binapi:"ip4_address,name=start" json:"start,omitempty"`
	End       ip_types.IP4Address `binapi:"ip4_address,name=end" json:"end,omitempty"`
	NameLen   uint8               `binapi:"u8,name=name_len" json:"name_len,omitempty"`
	Name      []byte              `binapi:"u8[64],name=name" json:"name,omitempty"`
	NwiLen    uint8               `binapi:"u8,name=nwi_len" json:"-"`
	Nwi       []byte              `binapi:"u8[nwi_len],name=nwi" json:"nwi,omitempty"`
}

func (m *UpfNatPoolAdd) Reset()               { *m = UpfNatPoolAdd{} }
func (*UpfNatPoolAdd) GetMessageName() string { return "upf_nat_pool_add" }
func (*UpfNatPoolAdd) GetCrcString() string   { return "53c81402" }
func (*UpfNatPoolAdd) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfNatPoolAdd) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1              // m.IsAdd
	size += 2              // m.MinPort
	size += 2              // m.MaxPort
	size += 4              // m.BlockSize
	size += 1 * 4          // m.Start
	size += 1 * 4          // m.End
	size += 1              // m.NameLen
	size += 1 * 64         // m.Name
	size += 1              // m.NwiLen
	size += 1 * len(m.Nwi) // m.Nwi
	return size
}
func (m *UpfNatPoolAdd) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint16(m.MinPort)
	buf.EncodeUint16(m.MaxPort)
	buf.EncodeUint32(m.BlockSize)
	buf.EncodeBytes(m.Start[:], 4)
	buf.EncodeBytes(m.End[:], 4)
	buf.EncodeUint8(m.NameLen)
	buf.EncodeBytes(m.Name, 64)
	buf.EncodeUint8(uint8(len(m.Nwi)))
	buf.EncodeBytes(m.Nwi, 0)
	return buf.Bytes(), nil
}
func (m *UpfNatPoolAdd) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.MinPort = buf.DecodeUint16()
	m.MaxPort = buf.DecodeUint16()
	m.BlockSize = buf.DecodeUint32()
	copy(m.Start[:], buf.DecodeBytes(4))
	copy(m.End[:], buf.DecodeBytes(4))
	m.NameLen = buf.DecodeUint8()
	m.Name = make([]byte, 64)
	copy(m.Name, buf.DecodeBytes(len(m.Name)))
	m.NwiLen = buf.DecodeUint8()
	m.Nwi = make([]byte, m.NwiLen)
	copy(m.Nwi, buf.DecodeBytes(len(m.Nwi)))
	return nil
}

// UpfNatPoolAddReply defines message 'upf_nat_pool_add_reply'.
type UpfNatPoolAddReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfNatPoolAddReply) Reset()               { *m = UpfNatPoolAddReply{} }
func (*UpfNatPoolAddReply) GetMessageName() string { return "upf_nat_pool_add_reply" }
func (*UpfNatPoolAddReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfNatPoolAddReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfNatPoolAddReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfNatPoolAddReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfNatPoolAddReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfNatPoolDetails defines message 'upf_nat_pool_details'.
type UpfNatPoolDetails struct {
	Name         []byte `binapi:"u8[64],name=name" json:"name,omitempty"`
	BlockSize    uint16 `binapi:"u16,name=block_size" json:"block_size,omitempty"`
	MaxUsers     uint32 `binapi:"u32,name=max_users" json:"max_users,omitempty"`
	CurrentUsers uint32 `binapi:"u32,name=current_users" json:"current_users,omitempty"`
	NwiLen       uint8  `binapi:"u8,name=nwi_len" json:"-"`
	Nwi          []byte `binapi:"u8[nwi_len],name=nwi" json:"nwi,omitempty"`
}

func (m *UpfNatPoolDetails) Reset()               { *m = UpfNatPoolDetails{} }
func (*UpfNatPoolDetails) GetMessageName() string { return "upf_nat_pool_details" }
func (*UpfNatPoolDetails) GetCrcString() string   { return "536a8c46" }
func (*UpfNatPoolDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfNatPoolDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 * 64         // m.Name
	size += 2              // m.BlockSize
	size += 4              // m.MaxUsers
	size += 4              // m.CurrentUsers
	size += 1              // m.NwiLen
	size += 1 * len(m.Nwi) // m.Nwi
	return size
}
func (m *UpfNatPoolDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBytes(m.Name, 64)
	buf.EncodeUint16(m.BlockSize)
	buf.EncodeUint32(m.MaxUsers)
	buf.EncodeUint32(m.CurrentUsers)
	buf.EncodeUint8(uint8(len(m.Nwi)))
	buf.EncodeBytes(m.Nwi, 0)
	return buf.Bytes(), nil
}
func (m *UpfNatPoolDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = make([]byte, 64)
	copy(m.Name, buf.DecodeBytes(len(m.Name)))
	m.BlockSize = buf.DecodeUint16()
	m.MaxUsers = buf.DecodeUint32()
	m.CurrentUsers = buf.DecodeUint32()
	m.NwiLen = buf.DecodeUint8()
	m.Nwi = make([]byte, m.NwiLen)
	copy(m.Nwi, buf.DecodeBytes(len(m.Nwi)))
	return nil
}

// UpfNatPoolDump defines message 'upf_nat_pool_dump'.
type UpfNatPoolDump struct{}

func (m *UpfNatPoolDump) Reset()               { *m = UpfNatPoolDump{} }
func (*UpfNatPoolDump) GetMessageName() string { return "upf_nat_pool_dump" }
func (*UpfNatPoolDump) GetCrcString() string   { return "51077d14" }
func (*UpfNatPoolDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfNatPoolDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfNatPoolDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfNatPoolDump) Unmarshal(b []byte) error {
	return nil
}

// UpfNwiAddDel defines message 'upf_nwi_add_del'.
type UpfNwiAddDel struct {
	Add                   uint8            `binapi:"u8,name=add" json:"add,omitempty"`
	IP4TableID            uint32           `binapi:"u32,name=ip4_table_id" json:"ip4_table_id,omitempty"`
	IP6TableID            uint32           `binapi:"u32,name=ip6_table_id" json:"ip6_table_id,omitempty"`
	TxIP4TableID          uint32           `binapi:"u32,name=tx_ip4_table_id" json:"tx_ip4_table_id,omitempty"`
	TxIP6TableID          uint32           `binapi:"u32,name=tx_ip6_table_id" json:"tx_ip6_table_id,omitempty"`
	IpfixPolicy           []byte           `binapi:"u8[64],name=ipfix_policy" json:"ipfix_policy,omitempty"`
	IpfixCollectorIP      ip_types.Address `binapi:"address,name=ipfix_collector_ip" json:"ipfix_collector_ip,omitempty"`
	IpfixReportInterval   uint32           `binapi:"u32,name=ipfix_report_interval" json:"ipfix_report_interval,omitempty"`
	ObservationDomainID   uint32           `binapi:"u32,name=observation_domain_id" json:"observation_domain_id,omitempty"`
	ObservationDomainName []byte           `binapi:"u8[256],name=observation_domain_name" json:"observation_domain_name,omitempty"`
	ObservationPointID    uint64           `binapi:"u64,name=observation_point_id" json:"observation_point_id,omitempty"`
	NwiLen                uint8            `binapi:"u8,name=nwi_len" json:"-"`
	Nwi                   []byte           `binapi:"u8[nwi_len],name=nwi" json:"nwi,omitempty"`
}

func (m *UpfNwiAddDel) Reset()               { *m = UpfNwiAddDel{} }
func (*UpfNwiAddDel) GetMessageName() string { return "upf_nwi_add_del" }
func (*UpfNwiAddDel) GetCrcString() string   { return "bc2ab757" }
func (*UpfNwiAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfNwiAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1              // m.Add
	size += 4              // m.IP4TableID
	size += 4              // m.IP6TableID
	size += 4              // m.TxIP4TableID
	size += 4              // m.TxIP6TableID
	size += 1 * 64         // m.IpfixPolicy
	size += 1              // m.IpfixCollectorIP.Af
	size += 1 * 16         // m.IpfixCollectorIP.Un
	size += 4              // m.IpfixReportInterval
	size += 4              // m.ObservationDomainID
	size += 1 * 256        // m.ObservationDomainName
	size += 8              // m.ObservationPointID
	size += 1              // m.NwiLen
	size += 1 * len(m.Nwi) // m.Nwi
	return size
}
func (m *UpfNwiAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(m.Add)
	buf.EncodeUint32(m.IP4TableID)
	buf.EncodeUint32(m.IP6TableID)
	buf.EncodeUint32(m.TxIP4TableID)
	buf.EncodeUint32(m.TxIP6TableID)
	buf.EncodeBytes(m.IpfixPolicy, 64)
	buf.EncodeUint8(uint8(m.IpfixCollectorIP.Af))
	buf.EncodeBytes(m.IpfixCollectorIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint32(m.IpfixReportInterval)
	buf.EncodeUint32(m.ObservationDomainID)
	buf.EncodeBytes(m.ObservationDomainName, 256)
	buf.EncodeUint64(m.ObservationPointID)
	buf.EncodeUint8(uint8(len(m.Nwi)))
	buf.EncodeBytes(m.Nwi, 0)
	return buf.Bytes(), nil
}
func (m *UpfNwiAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Add = buf.DecodeUint8()
	m.IP4TableID = buf.DecodeUint32()
	m.IP6TableID = buf.DecodeUint32()
	m.TxIP4TableID = buf.DecodeUint32()
	m.TxIP6TableID = buf.DecodeUint32()
	m.IpfixPolicy = make([]byte, 64)
	copy(m.IpfixPolicy, buf.DecodeBytes(len(m.IpfixPolicy)))
	m.IpfixCollectorIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.IpfixCollectorIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.IpfixReportInterval = buf.DecodeUint32()
	m.ObservationDomainID = buf.DecodeUint32()
	m.ObservationDomainName = make([]byte, 256)
	copy(m.ObservationDomainName, buf.DecodeBytes(len(m.ObservationDomainName)))
	m.ObservationPointID = buf.DecodeUint64()
	m.NwiLen = buf.DecodeUint8()
	m.Nwi = make([]byte, m.NwiLen)
	copy(m.Nwi, buf.DecodeBytes(len(m.Nwi)))
	return nil
}

// UpfNwiAddDelReply defines message 'upf_nwi_add_del_reply'.
type UpfNwiAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfNwiAddDelReply) Reset()               { *m = UpfNwiAddDelReply{} }
func (*UpfNwiAddDelReply) GetMessageName() string { return "upf_nwi_add_del_reply" }
func (*UpfNwiAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfNwiAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfNwiAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfNwiAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfNwiAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfNwiDetails defines message 'upf_nwi_details'.
type UpfNwiDetails struct {
	IP4TableID            uint32           `binapi:"u32,name=ip4_table_id" json:"ip4_table_id,omitempty"`
	IP6TableID            uint32           `binapi:"u32,name=ip6_table_id" json:"ip6_table_id,omitempty"`
	TxIP4TableID          uint32           `binapi:"u32,name=tx_ip4_table_id" json:"tx_ip4_table_id,omitempty"`
	TxIP6TableID          uint32           `binapi:"u32,name=tx_ip6_table_id" json:"tx_ip6_table_id,omitempty"`
	IpfixPolicy           []byte           `binapi:"u8[64],name=ipfix_policy" json:"ipfix_policy,omitempty"`
	IpfixCollectorIP      ip_types.Address `binapi:"address,name=ipfix_collector_ip" json:"ipfix_collector_ip,omitempty"`
	IpfixReportInterval   uint32           `binapi:"u32,name=ipfix_report_interval" json:"ipfix_report_interval,omitempty"`
	ObservationDomainID   uint32           `binapi:"u32,name=observation_domain_id" json:"observation_domain_id,omitempty"`
	ObservationDomainName []byte           `binapi:"u8[256],name=observation_domain_name" json:"observation_domain_name,omitempty"`
	ObservationPointID    uint64           `binapi:"u64,name=observation_point_id" json:"observation_point_id,omitempty"`
	NwiLen                uint8            `binapi:"u8,name=nwi_len" json:"-"`
	Nwi                   []byte           `binapi:"u8[nwi_len],name=nwi" json:"nwi,omitempty"`
}

func (m *UpfNwiDetails) Reset()               { *m = UpfNwiDetails{} }
func (*UpfNwiDetails) GetMessageName() string { return "upf_nwi_details" }
func (*UpfNwiDetails) GetCrcString() string   { return "b845bcf1" }
func (*UpfNwiDetails) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfNwiDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4              // m.IP4TableID
	size += 4              // m.IP6TableID
	size += 4              // m.TxIP4TableID
	size += 4              // m.TxIP6TableID
	size += 1 * 64         // m.IpfixPolicy
	size += 1              // m.IpfixCollectorIP.Af
	size += 1 * 16         // m.IpfixCollectorIP.Un
	size += 4              // m.IpfixReportInterval
	size += 4              // m.ObservationDomainID
	size += 1 * 256        // m.ObservationDomainName
	size += 8              // m.ObservationPointID
	size += 1              // m.NwiLen
	size += 1 * len(m.Nwi) // m.Nwi
	return size
}
func (m *UpfNwiDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.IP4TableID)
	buf.EncodeUint32(m.IP6TableID)
	buf.EncodeUint32(m.TxIP4TableID)
	buf.EncodeUint32(m.TxIP6TableID)
	buf.EncodeBytes(m.IpfixPolicy, 64)
	buf.EncodeUint8(uint8(m.IpfixCollectorIP.Af))
	buf.EncodeBytes(m.IpfixCollectorIP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint32(m.IpfixReportInterval)
	buf.EncodeUint32(m.ObservationDomainID)
	buf.EncodeBytes(m.ObservationDomainName, 256)
	buf.EncodeUint64(m.ObservationPointID)
	buf.EncodeUint8(uint8(len(m.Nwi)))
	buf.EncodeBytes(m.Nwi, 0)
	return buf.Bytes(), nil
}
func (m *UpfNwiDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IP4TableID = buf.DecodeUint32()
	m.IP6TableID = buf.DecodeUint32()
	m.TxIP4TableID = buf.DecodeUint32()
	m.TxIP6TableID = buf.DecodeUint32()
	m.IpfixPolicy = make([]byte, 64)
	copy(m.IpfixPolicy, buf.DecodeBytes(len(m.IpfixPolicy)))
	m.IpfixCollectorIP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.IpfixCollectorIP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.IpfixReportInterval = buf.DecodeUint32()
	m.ObservationDomainID = buf.DecodeUint32()
	m.ObservationDomainName = make([]byte, 256)
	copy(m.ObservationDomainName, buf.DecodeBytes(len(m.ObservationDomainName)))
	m.ObservationPointID = buf.DecodeUint64()
	m.NwiLen = buf.DecodeUint8()
	m.Nwi = make([]byte, m.NwiLen)
	copy(m.Nwi, buf.DecodeBytes(len(m.Nwi)))
	return nil
}

// UpfNwiDump defines message 'upf_nwi_dump'.
type UpfNwiDump struct{}

func (m *UpfNwiDump) Reset()               { *m = UpfNwiDump{} }
func (*UpfNwiDump) GetMessageName() string { return "upf_nwi_dump" }
func (*UpfNwiDump) GetCrcString() string   { return "51077d14" }
func (*UpfNwiDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfNwiDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfNwiDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfNwiDump) Unmarshal(b []byte) error {
	return nil
}

// UpfPfcpEndpointAddDel defines message 'upf_pfcp_endpoint_add_del'.
type UpfPfcpEndpointAddDel struct {
	IsAdd   uint8            `binapi:"u8,name=is_add" json:"is_add,omitempty"`
	TableID uint32           `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	IP      ip_types.Address `binapi:"address,name=ip" json:"ip,omitempty"`
}

func (m *UpfPfcpEndpointAddDel) Reset()               { *m = UpfPfcpEndpointAddDel{} }
func (*UpfPfcpEndpointAddDel) GetMessageName() string { return "upf_pfcp_endpoint_add_del" }
func (*UpfPfcpEndpointAddDel) GetCrcString() string   { return "c10b6079" }
func (*UpfPfcpEndpointAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpEndpointAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 4      // m.TableID
	size += 1      // m.IP.Af
	size += 1 * 16 // m.IP.Un
	return size
}
func (m *UpfPfcpEndpointAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(m.IsAdd)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(uint8(m.IP.Af))
	buf.EncodeBytes(m.IP.Un.XXX_UnionData[:], 16)
	return buf.Bytes(), nil
}
func (m *UpfPfcpEndpointAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeUint8()
	m.TableID = buf.DecodeUint32()
	m.IP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.IP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	return nil
}

// UpfPfcpEndpointAddDelReply defines message 'upf_pfcp_endpoint_add_del_reply'.
type UpfPfcpEndpointAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfPfcpEndpointAddDelReply) Reset()               { *m = UpfPfcpEndpointAddDelReply{} }
func (*UpfPfcpEndpointAddDelReply) GetMessageName() string { return "upf_pfcp_endpoint_add_del_reply" }
func (*UpfPfcpEndpointAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfPfcpEndpointAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfPfcpEndpointAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfPfcpEndpointAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfPfcpEndpointAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfPfcpEndpointDetails defines message 'upf_pfcp_endpoint_details'.
type UpfPfcpEndpointDetails struct {
	TableID uint32           `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	IP      ip_types.Address `binapi:"address,name=ip" json:"ip,omitempty"`
}

func (m *UpfPfcpEndpointDetails) Reset()               { *m = UpfPfcpEndpointDetails{} }
func (*UpfPfcpEndpointDetails) GetMessageName() string { return "upf_pfcp_endpoint_details" }
func (*UpfPfcpEndpointDetails) GetCrcString() string   { return "84b7ba70" }
func (*UpfPfcpEndpointDetails) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpEndpointDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.TableID
	size += 1      // m.IP.Af
	size += 1 * 16 // m.IP.Un
	return size
}
func (m *UpfPfcpEndpointDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(uint8(m.IP.Af))
	buf.EncodeBytes(m.IP.Un.XXX_UnionData[:], 16)
	return buf.Bytes(), nil
}
func (m *UpfPfcpEndpointDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TableID = buf.DecodeUint32()
	m.IP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.IP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	return nil
}

// UpfPfcpEndpointDump defines message 'upf_pfcp_endpoint_dump'.
type UpfPfcpEndpointDump struct{}

func (m *UpfPfcpEndpointDump) Reset()               { *m = UpfPfcpEndpointDump{} }
func (*UpfPfcpEndpointDump) GetMessageName() string { return "upf_pfcp_endpoint_dump" }
func (*UpfPfcpEndpointDump) GetCrcString() string   { return "51077d14" }
func (*UpfPfcpEndpointDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpEndpointDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfPfcpEndpointDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfPfcpEndpointDump) Unmarshal(b []byte) error {
	return nil
}

// UpfPfcpFormat defines message 'upf_pfcp_format'.
type UpfPfcpFormat struct {
	PacketLen uint32 `binapi:"u32,name=packet_len" json:"-"`
	Packet    []byte `binapi:"u8[packet_len],name=packet" json:"packet,omitempty"`
}

func (m *UpfPfcpFormat) Reset()               { *m = UpfPfcpFormat{} }
func (*UpfPfcpFormat) GetMessageName() string { return "upf_pfcp_format" }
func (*UpfPfcpFormat) GetCrcString() string   { return "d522d6e1" }
func (*UpfPfcpFormat) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpFormat) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4                 // m.PacketLen
	size += 1 * len(m.Packet) // m.Packet
	return size
}
func (m *UpfPfcpFormat) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(len(m.Packet)))
	buf.EncodeBytes(m.Packet, 0)
	return buf.Bytes(), nil
}
func (m *UpfPfcpFormat) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PacketLen = buf.DecodeUint32()
	m.Packet = make([]byte, m.PacketLen)
	copy(m.Packet, buf.DecodeBytes(len(m.Packet)))
	return nil
}

// UpfPfcpFormatReply defines message 'upf_pfcp_format_reply'.
type UpfPfcpFormatReply struct {
	Retval  int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	TextLen uint32 `binapi:"u32,name=text_len" json:"-"`
	Text    []byte `binapi:"u8[text_len],name=text" json:"text,omitempty"`
}

func (m *UpfPfcpFormatReply) Reset()               { *m = UpfPfcpFormatReply{} }
func (*UpfPfcpFormatReply) GetMessageName() string { return "upf_pfcp_format_reply" }
func (*UpfPfcpFormatReply) GetCrcString() string   { return "8706f872" }
func (*UpfPfcpFormatReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfPfcpFormatReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4               // m.Retval
	size += 4               // m.TextLen
	size += 1 * len(m.Text) // m.Text
	return size
}
func (m *UpfPfcpFormatReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(uint32(len(m.Text)))
	buf.EncodeBytes(m.Text, 0)
	return buf.Bytes(), nil
}
func (m *UpfPfcpFormatReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.TextLen = buf.DecodeUint32()
	m.Text = make([]byte, m.TextLen)
	copy(m.Text, buf.DecodeBytes(len(m.Text)))
	return nil
}

// UpfPfcpHeartbeatsGet defines message 'upf_pfcp_heartbeats_get'.
type UpfPfcpHeartbeatsGet struct{}

func (m *UpfPfcpHeartbeatsGet) Reset()               { *m = UpfPfcpHeartbeatsGet{} }
func (*UpfPfcpHeartbeatsGet) GetMessageName() string { return "upf_pfcp_heartbeats_get" }
func (*UpfPfcpHeartbeatsGet) GetCrcString() string   { return "51077d14" }
func (*UpfPfcpHeartbeatsGet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpHeartbeatsGet) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfPfcpHeartbeatsGet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfPfcpHeartbeatsGet) Unmarshal(b []byte) error {
	return nil
}

// UpfPfcpHeartbeatsGetReply defines message 'upf_pfcp_heartbeats_get_reply'.
type UpfPfcpHeartbeatsGetReply struct {
	Timeout uint32 `binapi:"u32,name=timeout" json:"timeout,omitempty"`
	Retries uint32 `binapi:"u32,name=retries" json:"retries,omitempty"`
}

func (m *UpfPfcpHeartbeatsGetReply) Reset()               { *m = UpfPfcpHeartbeatsGetReply{} }
func (*UpfPfcpHeartbeatsGetReply) GetMessageName() string { return "upf_pfcp_heartbeats_get_reply" }
func (*UpfPfcpHeartbeatsGetReply) GetCrcString() string   { return "f5eafa3d" }
func (*UpfPfcpHeartbeatsGetReply) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpHeartbeatsGetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Timeout
	size += 4 // m.Retries
	return size
}
func (m *UpfPfcpHeartbeatsGetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.Timeout)
	buf.EncodeUint32(m.Retries)
	return buf.Bytes(), nil
}
func (m *UpfPfcpHeartbeatsGetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Timeout = buf.DecodeUint32()
	m.Retries = buf.DecodeUint32()
	return nil
}

// UpfPfcpHeartbeatsSet defines message 'upf_pfcp_heartbeats_set'.
type UpfPfcpHeartbeatsSet struct {
	Timeout uint32 `binapi:"u32,name=timeout" json:"timeout,omitempty"`
	Retries uint32 `binapi:"u32,name=retries" json:"retries,omitempty"`
}

func (m *UpfPfcpHeartbeatsSet) Reset()               { *m = UpfPfcpHeartbeatsSet{} }
func (*UpfPfcpHeartbeatsSet) GetMessageName() string { return "upf_pfcp_heartbeats_set" }
func (*UpfPfcpHeartbeatsSet) GetCrcString() string   { return "f5eafa3d" }
func (*UpfPfcpHeartbeatsSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpHeartbeatsSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Timeout
	size += 4 // m.Retries
	return size
}
func (m *UpfPfcpHeartbeatsSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.Timeout)
	buf.EncodeUint32(m.Retries)
	return buf.Bytes(), nil
}
func (m *UpfPfcpHeartbeatsSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Timeout = buf.DecodeUint32()
	m.Retries = buf.DecodeUint32()
	return nil
}

// UpfPfcpHeartbeatsSetReply defines message 'upf_pfcp_heartbeats_set_reply'.
type UpfPfcpHeartbeatsSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfPfcpHeartbeatsSetReply) Reset()               { *m = UpfPfcpHeartbeatsSetReply{} }
func (*UpfPfcpHeartbeatsSetReply) GetMessageName() string { return "upf_pfcp_heartbeats_set_reply" }
func (*UpfPfcpHeartbeatsSetReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfPfcpHeartbeatsSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfPfcpHeartbeatsSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfPfcpHeartbeatsSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfPfcpHeartbeatsSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfPfcpReencode defines message 'upf_pfcp_reencode'.
type UpfPfcpReencode struct {
	PacketLen uint32 `binapi:"u32,name=packet_len" json:"-"`
	Packet    []byte `binapi:"u8[packet_len],name=packet" json:"packet,omitempty"`
}

func (m *UpfPfcpReencode) Reset()               { *m = UpfPfcpReencode{} }
func (*UpfPfcpReencode) GetMessageName() string { return "upf_pfcp_reencode" }
func (*UpfPfcpReencode) GetCrcString() string   { return "d522d6e1" }
func (*UpfPfcpReencode) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpReencode) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4                 // m.PacketLen
	size += 1 * len(m.Packet) // m.Packet
	return size
}
func (m *UpfPfcpReencode) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(len(m.Packet)))
	buf.EncodeBytes(m.Packet, 0)
	return buf.Bytes(), nil
}
func (m *UpfPfcpReencode) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.PacketLen = buf.DecodeUint32()
	m.Packet = make([]byte, m.PacketLen)
	copy(m.Packet, buf.DecodeBytes(len(m.Packet)))
	return nil
}

// UpfPfcpReencodeReply defines message 'upf_pfcp_reencode_reply'.
type UpfPfcpReencodeReply struct {
	Retval    int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	PacketLen uint32 `binapi:"u32,name=packet_len" json:"-"`
	Packet    []byte `binapi:"u8[packet_len],name=packet" json:"packet,omitempty"`
}

func (m *UpfPfcpReencodeReply) Reset()               { *m = UpfPfcpReencodeReply{} }
func (*UpfPfcpReencodeReply) GetMessageName() string { return "upf_pfcp_reencode_reply" }
func (*UpfPfcpReencodeReply) GetCrcString() string   { return "68800422" }
func (*UpfPfcpReencodeReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfPfcpReencodeReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4                 // m.Retval
	size += 4                 // m.PacketLen
	size += 1 * len(m.Packet) // m.Packet
	return size
}
func (m *UpfPfcpReencodeReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(uint32(len(m.Packet)))
	buf.EncodeBytes(m.Packet, 0)
	return buf.Bytes(), nil
}
func (m *UpfPfcpReencodeReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.PacketLen = buf.DecodeUint32()
	m.Packet = make([]byte, m.PacketLen)
	copy(m.Packet, buf.DecodeBytes(len(m.Packet)))
	return nil
}

// UpfPfcpServerSet defines message 'upf_pfcp_server_set'.
type UpfPfcpServerSet struct {
	FifoSize      uint32 `binapi:"u32,name=fifo_size" json:"fifo_size,omitempty"`
	PreallocFifos uint32 `binapi:"u32,name=prealloc_fifos" json:"prealloc_fifos,omitempty"`
	SegmentSize   uint32 `binapi:"u32,name=segment_size" json:"segment_size,omitempty"`
}

func (m *UpfPfcpServerSet) Reset()               { *m = UpfPfcpServerSet{} }
func (*UpfPfcpServerSet) GetMessageName() string { return "upf_pfcp_server_set" }
func (*UpfPfcpServerSet) GetCrcString() string   { return "747f398b" }
func (*UpfPfcpServerSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpServerSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.FifoSize
	size += 4 // m.PreallocFifos
	size += 4 // m.SegmentSize
	return size
}
func (m *UpfPfcpServerSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.FifoSize)
	buf.EncodeUint32(m.PreallocFifos)
	buf.EncodeUint32(m.SegmentSize)
	return buf.Bytes(), nil
}
func (m *UpfPfcpServerSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.FifoSize = buf.DecodeUint32()
	m.PreallocFifos = buf.DecodeUint32()
	m.SegmentSize = buf.DecodeUint32()
	return nil
}

// UpfPfcpServerSetReply defines message 'upf_pfcp_server_set_reply'.
type UpfPfcpServerSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfPfcpServerSetReply) Reset()               { *m = UpfPfcpServerSetReply{} }
func (*UpfPfcpServerSetReply) GetMessageName() string { return "upf_pfcp_server_set_reply" }
func (*UpfPfcpServerSetReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfPfcpServerSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfPfcpServerSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfPfcpServerSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfPfcpServerSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfPfcpServerShow defines message 'upf_pfcp_server_show'.
type UpfPfcpServerShow struct{}

func (m *UpfPfcpServerShow) Reset()               { *m = UpfPfcpServerShow{} }
func (*UpfPfcpServerShow) GetMessageName() string { return "upf_pfcp_server_show" }
func (*UpfPfcpServerShow) GetCrcString() string   { return "51077d14" }
func (*UpfPfcpServerShow) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpServerShow) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfPfcpServerShow) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfPfcpServerShow) Unmarshal(b []byte) error {
	return nil
}

// UpfPfcpServerShowReply defines message 'upf_pfcp_server_show_reply'.
type UpfPfcpServerShowReply struct {
	FifoSize      uint32 `binapi:"u32,name=fifo_size" json:"fifo_size,omitempty"`
	PreallocFifos uint32 `binapi:"u32,name=prealloc_fifos" json:"prealloc_fifos,omitempty"`
	SegmentSize   uint32 `binapi:"u32,name=segment_size" json:"segment_size,omitempty"`
}

func (m *UpfPfcpServerShowReply) Reset()               { *m = UpfPfcpServerShowReply{} }
func (*UpfPfcpServerShowReply) GetMessageName() string { return "upf_pfcp_server_show_reply" }
func (*UpfPfcpServerShowReply) GetCrcString() string   { return "747f398b" }
func (*UpfPfcpServerShowReply) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPfcpServerShowReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.FifoSize
	size += 4 // m.PreallocFifos
	size += 4 // m.SegmentSize
	return size
}
func (m *UpfPfcpServerShowReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.FifoSize)
	buf.EncodeUint32(m.PreallocFifos)
	buf.EncodeUint32(m.SegmentSize)
	return buf.Bytes(), nil
}
func (m *UpfPfcpServerShowReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.FifoSize = buf.DecodeUint32()
	m.PreallocFifos = buf.DecodeUint32()
	m.SegmentSize = buf.DecodeUint32()
	return nil
}

// UpfPolicyAddDel defines message 'upf_policy_add_del'.
type UpfPolicyAddDel struct {
	Action     uint8  `binapi:"u8,name=action" json:"action,omitempty"`
	Identifier string `binapi:"string[64],name=identifier" json:"identifier,omitempty"`
	IP4TableID uint32 `binapi:"u32,name=ip4_table_id" json:"ip4_table_id,omitempty"`
	IP6TableID uint32 `binapi:"u32,name=ip6_table_id" json:"ip6_table_id,omitempty"`
}

func (m *UpfPolicyAddDel) Reset()               { *m = UpfPolicyAddDel{} }
func (*UpfPolicyAddDel) GetMessageName() string { return "upf_policy_add_del" }
func (*UpfPolicyAddDel) GetCrcString() string   { return "111c586f" }
func (*UpfPolicyAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPolicyAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1  // m.Action
	size += 64 // m.Identifier
	size += 4  // m.IP4TableID
	size += 4  // m.IP6TableID
	return size
}
func (m *UpfPolicyAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(m.Action)
	buf.EncodeString(m.Identifier, 64)
	buf.EncodeUint32(m.IP4TableID)
	buf.EncodeUint32(m.IP6TableID)
	return buf.Bytes(), nil
}
func (m *UpfPolicyAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Action = buf.DecodeUint8()
	m.Identifier = buf.DecodeString(64)
	m.IP4TableID = buf.DecodeUint32()
	m.IP6TableID = buf.DecodeUint32()
	return nil
}

// UpfPolicyAddDelReply defines message 'upf_policy_add_del_reply'.
type UpfPolicyAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfPolicyAddDelReply) Reset()               { *m = UpfPolicyAddDelReply{} }
func (*UpfPolicyAddDelReply) GetMessageName() string { return "upf_policy_add_del_reply" }
func (*UpfPolicyAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfPolicyAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfPolicyAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfPolicyAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfPolicyAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfPolicyDetails defines message 'upf_policy_details'.
type UpfPolicyDetails struct {
	Identifier string `binapi:"string[64],name=identifier" json:"identifier,omitempty"`
	IP4TableID uint32 `binapi:"u32,name=ip4_table_id" json:"ip4_table_id,omitempty"`
	IP6TableID uint32 `binapi:"u32,name=ip6_table_id" json:"ip6_table_id,omitempty"`
}

func (m *UpfPolicyDetails) Reset()               { *m = UpfPolicyDetails{} }
func (*UpfPolicyDetails) GetMessageName() string { return "upf_policy_details" }
func (*UpfPolicyDetails) GetCrcString() string   { return "1ee6f85d" }
func (*UpfPolicyDetails) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPolicyDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Identifier
	size += 4  // m.IP4TableID
	size += 4  // m.IP6TableID
	return size
}
func (m *UpfPolicyDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Identifier, 64)
	buf.EncodeUint32(m.IP4TableID)
	buf.EncodeUint32(m.IP6TableID)
	return buf.Bytes(), nil
}
func (m *UpfPolicyDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Identifier = buf.DecodeString(64)
	m.IP4TableID = buf.DecodeUint32()
	m.IP6TableID = buf.DecodeUint32()
	return nil
}

// UpfPolicyDump defines message 'upf_policy_dump'.
type UpfPolicyDump struct{}

func (m *UpfPolicyDump) Reset()               { *m = UpfPolicyDump{} }
func (*UpfPolicyDump) GetMessageName() string { return "upf_policy_dump" }
func (*UpfPolicyDump) GetCrcString() string   { return "51077d14" }
func (*UpfPolicyDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfPolicyDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfPolicyDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfPolicyDump) Unmarshal(b []byte) error {
	return nil
}

// UpfSetNodeID defines message 'upf_set_node_id'.
type UpfSetNodeID struct {
	Type    uint8            `binapi:"u8,name=type" json:"type,omitempty"`
	IP      ip_types.Address `binapi:"address,name=ip" json:"ip,omitempty"`
	FqdnLen uint8            `binapi:"u8,name=fqdn_len" json:"-"`
	Fqdn    []byte           `binapi:"u8[fqdn_len],name=fqdn" json:"fqdn,omitempty"`
}

func (m *UpfSetNodeID) Reset()               { *m = UpfSetNodeID{} }
func (*UpfSetNodeID) GetMessageName() string { return "upf_set_node_id" }
func (*UpfSetNodeID) GetCrcString() string   { return "d2f43a0a" }
func (*UpfSetNodeID) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfSetNodeID) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1               // m.Type
	size += 1               // m.IP.Af
	size += 1 * 16          // m.IP.Un
	size += 1               // m.FqdnLen
	size += 1 * len(m.Fqdn) // m.Fqdn
	return size
}
func (m *UpfSetNodeID) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(m.Type)
	buf.EncodeUint8(uint8(m.IP.Af))
	buf.EncodeBytes(m.IP.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(uint8(len(m.Fqdn)))
	buf.EncodeBytes(m.Fqdn, 0)
	return buf.Bytes(), nil
}
func (m *UpfSetNodeID) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Type = buf.DecodeUint8()
	m.IP.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.IP.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.FqdnLen = buf.DecodeUint8()
	m.Fqdn = make([]byte, m.FqdnLen)
	copy(m.Fqdn, buf.DecodeBytes(len(m.Fqdn)))
	return nil
}

// UpfSetNodeIDReply defines message 'upf_set_node_id_reply'.
type UpfSetNodeIDReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfSetNodeIDReply) Reset()               { *m = UpfSetNodeIDReply{} }
func (*UpfSetNodeIDReply) GetMessageName() string { return "upf_set_node_id_reply" }
func (*UpfSetNodeIDReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfSetNodeIDReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfSetNodeIDReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfSetNodeIDReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfSetNodeIDReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfShowUeipExport defines message 'upf_show_ueip_export'.
type UpfShowUeipExport struct{}

func (m *UpfShowUeipExport) Reset()               { *m = UpfShowUeipExport{} }
func (*UpfShowUeipExport) GetMessageName() string { return "upf_show_ueip_export" }
func (*UpfShowUeipExport) GetCrcString() string   { return "51077d14" }
func (*UpfShowUeipExport) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfShowUeipExport) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfShowUeipExport) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfShowUeipExport) Unmarshal(b []byte) error {
	return nil
}

// UpfShowUeipExportReply defines message 'upf_show_ueip_export_reply'.
type UpfShowUeipExportReply struct {
	Enabled   bool   `binapi:"bool,name=enabled" json:"enabled,omitempty"`
	TableID   uint32 `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	IfNameLen uint8  `binapi:"u8,name=if_name_len" json:"if_name_len,omitempty"`
	IfName    []byte `binapi:"u8[64],name=if_name" json:"if_name,omitempty"`
	NsPathLen uint8  `binapi:"u8,name=ns_path_len" json:"-"`
	NsPath    []byte `binapi:"u8[ns_path_len],name=ns_path" json:"ns_path,omitempty"`
}

func (m *UpfShowUeipExportReply) Reset()               { *m = UpfShowUeipExportReply{} }
func (*UpfShowUeipExportReply) GetMessageName() string { return "upf_show_ueip_export_reply" }
func (*UpfShowUeipExportReply) GetCrcString() string   { return "7aac337e" }
func (*UpfShowUeipExportReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfShowUeipExportReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1                 // m.Enabled
	size += 4                 // m.TableID
	size += 1                 // m.IfNameLen
	size += 1 * 64            // m.IfName
	size += 1                 // m.NsPathLen
	size += 1 * len(m.NsPath) // m.NsPath
	return size
}
func (m *UpfShowUeipExportReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.Enabled)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(m.IfNameLen)
	buf.EncodeBytes(m.IfName, 64)
	buf.EncodeUint8(uint8(len(m.NsPath)))
	buf.EncodeBytes(m.NsPath, 0)
	return buf.Bytes(), nil
}
func (m *UpfShowUeipExportReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Enabled = buf.DecodeBool()
	m.TableID = buf.DecodeUint32()
	m.IfNameLen = buf.DecodeUint8()
	m.IfName = make([]byte, 64)
	copy(m.IfName, buf.DecodeBytes(len(m.IfName)))
	m.NsPathLen = buf.DecodeUint8()
	m.NsPath = make([]byte, m.NsPathLen)
	copy(m.NsPath, buf.DecodeBytes(len(m.NsPath)))
	return nil
}

// UpfTdfUlEnableDisable defines message 'upf_tdf_ul_enable_disable'.
type UpfTdfUlEnableDisable struct {
	Enable    bool                           `binapi:"bool,name=enable" json:"enable,omitempty"`
	Interface interface_types.InterfaceIndex `binapi:"interface_index,name=interface" json:"interface,omitempty"`
	IsIPv6    bool                           `binapi:"bool,name=is_ipv6" json:"is_ipv6,omitempty"`
}

func (m *UpfTdfUlEnableDisable) Reset()               { *m = UpfTdfUlEnableDisable{} }
func (*UpfTdfUlEnableDisable) GetMessageName() string { return "upf_tdf_ul_enable_disable" }
func (*UpfTdfUlEnableDisable) GetCrcString() string   { return "53c1a78f" }
func (*UpfTdfUlEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfTdfUlEnableDisable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.Enable
	size += 4 // m.Interface
	size += 1 // m.IsIPv6
	return size
}
func (m *UpfTdfUlEnableDisable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.Enable)
	buf.EncodeUint32(uint32(m.Interface))
	buf.EncodeBool(m.IsIPv6)
	return buf.Bytes(), nil
}
func (m *UpfTdfUlEnableDisable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Enable = buf.DecodeBool()
	m.Interface = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.IsIPv6 = buf.DecodeBool()
	return nil
}

// UpfTdfUlEnableDisableReply defines message 'upf_tdf_ul_enable_disable_reply'.
type UpfTdfUlEnableDisableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfTdfUlEnableDisableReply) Reset()               { *m = UpfTdfUlEnableDisableReply{} }
func (*UpfTdfUlEnableDisableReply) GetMessageName() string { return "upf_tdf_ul_enable_disable_reply" }
func (*UpfTdfUlEnableDisableReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfTdfUlEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfTdfUlEnableDisableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfTdfUlEnableDisableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfTdfUlEnableDisableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfTdfUlTable defines message 'upf_tdf_ul_table'.
type UpfTdfUlTable struct {
	IsIPv6 bool `binapi:"bool,name=is_ipv6" json:"is_ipv6,omitempty"`
}

func (m *UpfTdfUlTable) Reset()               { *m = UpfTdfUlTable{} }
func (*UpfTdfUlTable) GetMessageName() string { return "upf_tdf_ul_table" }
func (*UpfTdfUlTable) GetCrcString() string   { return "98d231ca" }
func (*UpfTdfUlTable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfTdfUlTable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.IsIPv6
	return size
}
func (m *UpfTdfUlTable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsIPv6)
	return buf.Bytes(), nil
}
func (m *UpfTdfUlTable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsIPv6 = buf.DecodeBool()
	return nil
}

// UpfTdfUlTableAdd defines message 'upf_tdf_ul_table_add'.
type UpfTdfUlTableAdd struct {
	IsAdd            bool   `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	IsIPv6           bool   `binapi:"bool,name=is_ipv6" json:"is_ipv6,omitempty"`
	TableID          uint32 `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	SrcLookupTableID uint32 `binapi:"u32,name=src_lookup_table_id" json:"src_lookup_table_id,omitempty"`
}

func (m *UpfTdfUlTableAdd) Reset()               { *m = UpfTdfUlTableAdd{} }
func (*UpfTdfUlTableAdd) GetMessageName() string { return "upf_tdf_ul_table_add" }
func (*UpfTdfUlTableAdd) GetCrcString() string   { return "040a316b" }
func (*UpfTdfUlTableAdd) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfTdfUlTableAdd) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.IsAdd
	size += 1 // m.IsIPv6
	size += 4 // m.TableID
	size += 4 // m.SrcLookupTableID
	return size
}
func (m *UpfTdfUlTableAdd) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeBool(m.IsIPv6)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint32(m.SrcLookupTableID)
	return buf.Bytes(), nil
}
func (m *UpfTdfUlTableAdd) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.IsIPv6 = buf.DecodeBool()
	m.TableID = buf.DecodeUint32()
	m.SrcLookupTableID = buf.DecodeUint32()
	return nil
}

// UpfTdfUlTableAddReply defines message 'upf_tdf_ul_table_add_reply'.
type UpfTdfUlTableAddReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfTdfUlTableAddReply) Reset()               { *m = UpfTdfUlTableAddReply{} }
func (*UpfTdfUlTableAddReply) GetMessageName() string { return "upf_tdf_ul_table_add_reply" }
func (*UpfTdfUlTableAddReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfTdfUlTableAddReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfTdfUlTableAddReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfTdfUlTableAddReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfTdfUlTableAddReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfTdfUlTableReply defines message 'upf_tdf_ul_table_reply'.
type UpfTdfUlTableReply struct {
	MappingsLen uint8    `binapi:"u8,name=mappings_len" json:"-"`
	Mappings    []uint32 `binapi:"u32[mappings_len],name=mappings" json:"mappings,omitempty"`
}

func (m *UpfTdfUlTableReply) Reset()               { *m = UpfTdfUlTableReply{} }
func (*UpfTdfUlTableReply) GetMessageName() string { return "upf_tdf_ul_table_reply" }
func (*UpfTdfUlTableReply) GetCrcString() string   { return "d1a9fc2e" }
func (*UpfTdfUlTableReply) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfTdfUlTableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1                   // m.MappingsLen
	size += 4 * len(m.Mappings) // m.Mappings
	return size
}
func (m *UpfTdfUlTableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(uint8(len(m.Mappings)))
	for i := 0; i < len(m.Mappings); i++ {
		var x uint32
		if i < len(m.Mappings) {
			x = uint32(m.Mappings[i])
		}
		buf.EncodeUint32(x)
	}
	return buf.Bytes(), nil
}
func (m *UpfTdfUlTableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.MappingsLen = buf.DecodeUint8()
	m.Mappings = make([]uint32, m.MappingsLen)
	for i := 0; i < len(m.Mappings); i++ {
		m.Mappings[i] = buf.DecodeUint32()
	}
	return nil
}

// UpfUeipExportEnable defines message 'upf_ueip_export_enable'.
type UpfUeipExportEnable struct {
	IsEnable  bool   `binapi:"bool,name=is_enable" json:"is_enable,omitempty"`
	TableID   uint32 `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	IfNameLen uint8  `binapi:"u8,name=if_name_len" json:"if_name_len,omitempty"`
	IfName    []byte `binapi:"u8[64],name=if_name" json:"if_name,omitempty"`
	NsPathLen uint8  `binapi:"u8,name=ns_path_len" json:"-"`
	NsPath    []byte `binapi:"u8[ns_path_len],name=ns_path" json:"ns_path,omitempty"`
}

func (m *UpfUeipExportEnable) Reset()               { *m = UpfUeipExportEnable{} }
func (*UpfUeipExportEnable) GetMessageName() string { return "upf_ueip_export_enable" }
func (*UpfUeipExportEnable) GetCrcString() string   { return "77bf746e" }
func (*UpfUeipExportEnable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfUeipExportEnable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1                 // m.IsEnable
	size += 4                 // m.TableID
	size += 1                 // m.IfNameLen
	size += 1 * 64            // m.IfName
	size += 1                 // m.NsPathLen
	size += 1 * len(m.NsPath) // m.NsPath
	return size
}
func (m *UpfUeipExportEnable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsEnable)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(m.IfNameLen)
	buf.EncodeBytes(m.IfName, 64)
	buf.EncodeUint8(uint8(len(m.NsPath)))
	buf.EncodeBytes(m.NsPath, 0)
	return buf.Bytes(), nil
}
func (m *UpfUeipExportEnable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsEnable = buf.DecodeBool()
	m.TableID = buf.DecodeUint32()
	m.IfNameLen = buf.DecodeUint8()
	m.IfName = make([]byte, 64)
	copy(m.IfName, buf.DecodeBytes(len(m.IfName)))
	m.NsPathLen = buf.DecodeUint8()
	m.NsPath = make([]byte, m.NsPathLen)
	copy(m.NsPath, buf.DecodeBytes(len(m.NsPath)))
	return nil
}

// UpfUeipExportEnableReply defines message 'upf_ueip_export_enable_reply'.
type UpfUeipExportEnableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfUeipExportEnableReply) Reset()               { *m = UpfUeipExportEnableReply{} }
func (*UpfUeipExportEnableReply) GetMessageName() string { return "upf_ueip_export_enable_reply" }
func (*UpfUeipExportEnableReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfUeipExportEnableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfUeipExportEnableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfUeipExportEnableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfUeipExportEnableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// UpfUeipPoolDetails defines message 'upf_ueip_pool_details'.
type UpfUeipPoolDetails struct {
	IdentityLen uint8  `binapi:"u8,name=identity_len" json:"identity_len,omitempty"`
	Identity    []byte `binapi:"u8[64],name=identity" json:"identity,omitempty"`
	NwiNameLen  uint8  `binapi:"u8,name=nwi_name_len" json:"-"`
	NwiName     []byte `binapi:"u8[nwi_name_len],name=nwi_name" json:"nwi_name,omitempty"`
}

func (m *UpfUeipPoolDetails) Reset()               { *m = UpfUeipPoolDetails{} }
func (*UpfUeipPoolDetails) GetMessageName() string { return "upf_ueip_pool_details" }
func (*UpfUeipPoolDetails) GetCrcString() string   { return "b4a36a1c" }
func (*UpfUeipPoolDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfUeipPoolDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1                  // m.IdentityLen
	size += 1 * 64             // m.Identity
	size += 1                  // m.NwiNameLen
	size += 1 * len(m.NwiName) // m.NwiName
	return size
}
func (m *UpfUeipPoolDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(m.IdentityLen)
	buf.EncodeBytes(m.Identity, 64)
	buf.EncodeUint8(uint8(len(m.NwiName)))
	buf.EncodeBytes(m.NwiName, 0)
	return buf.Bytes(), nil
}
func (m *UpfUeipPoolDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IdentityLen = buf.DecodeUint8()
	m.Identity = make([]byte, 64)
	copy(m.Identity, buf.DecodeBytes(len(m.Identity)))
	m.NwiNameLen = buf.DecodeUint8()
	m.NwiName = make([]byte, m.NwiNameLen)
	copy(m.NwiName, buf.DecodeBytes(len(m.NwiName)))
	return nil
}

// UpfUeipPoolDump defines message 'upf_ueip_pool_dump'.
type UpfUeipPoolDump struct{}

func (m *UpfUeipPoolDump) Reset()               { *m = UpfUeipPoolDump{} }
func (*UpfUeipPoolDump) GetMessageName() string { return "upf_ueip_pool_dump" }
func (*UpfUeipPoolDump) GetCrcString() string   { return "51077d14" }
func (*UpfUeipPoolDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfUeipPoolDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *UpfUeipPoolDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *UpfUeipPoolDump) Unmarshal(b []byte) error {
	return nil
}

// UpfUeipPoolNwiAdd defines message 'upf_ueip_pool_nwi_add'.
type UpfUeipPoolNwiAdd struct {
	IsAdd       bool   `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	IdentityLen uint8  `binapi:"u8,name=identity_len" json:"identity_len,omitempty"`
	Identity    []byte `binapi:"u8[64],name=identity" json:"identity,omitempty"`
	NwiNameLen  uint8  `binapi:"u8,name=nwi_name_len" json:"-"`
	NwiName     []byte `binapi:"u8[nwi_name_len],name=nwi_name" json:"nwi_name,omitempty"`
}

func (m *UpfUeipPoolNwiAdd) Reset()               { *m = UpfUeipPoolNwiAdd{} }
func (*UpfUeipPoolNwiAdd) GetMessageName() string { return "upf_ueip_pool_nwi_add" }
func (*UpfUeipPoolNwiAdd) GetCrcString() string   { return "31b44993" }
func (*UpfUeipPoolNwiAdd) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *UpfUeipPoolNwiAdd) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1                  // m.IsAdd
	size += 1                  // m.IdentityLen
	size += 1 * 64             // m.Identity
	size += 1                  // m.NwiNameLen
	size += 1 * len(m.NwiName) // m.NwiName
	return size
}
func (m *UpfUeipPoolNwiAdd) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint8(m.IdentityLen)
	buf.EncodeBytes(m.Identity, 64)
	buf.EncodeUint8(uint8(len(m.NwiName)))
	buf.EncodeBytes(m.NwiName, 0)
	return buf.Bytes(), nil
}
func (m *UpfUeipPoolNwiAdd) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.IdentityLen = buf.DecodeUint8()
	m.Identity = make([]byte, 64)
	copy(m.Identity, buf.DecodeBytes(len(m.Identity)))
	m.NwiNameLen = buf.DecodeUint8()
	m.NwiName = make([]byte, m.NwiNameLen)
	copy(m.NwiName, buf.DecodeBytes(len(m.NwiName)))
	return nil
}

// UpfUeipPoolNwiAddReply defines message 'upf_ueip_pool_nwi_add_reply'.
type UpfUeipPoolNwiAddReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *UpfUeipPoolNwiAddReply) Reset()               { *m = UpfUeipPoolNwiAddReply{} }
func (*UpfUeipPoolNwiAddReply) GetMessageName() string { return "upf_ueip_pool_nwi_add_reply" }
func (*UpfUeipPoolNwiAddReply) GetCrcString() string   { return "e8d4e804" }
func (*UpfUeipPoolNwiAddReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *UpfUeipPoolNwiAddReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *UpfUeipPoolNwiAddReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *UpfUeipPoolNwiAddReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_upf_binapi_init() }
func file_upf_binapi_init() {
	api.RegisterMessage((*AdfActiveVersionDetails)(nil), "adf_active_version_details_85a4f8a6")
	api.RegisterMessage((*AdfActiveVersionDump)(nil), "adf_active_version_dump_396ae46d")
	api.RegisterMessage((*AdfAddIPRule)(nil), "adf_add_ip_rule_63c56102")
	api.RegisterMessage((*AdfAddIPRuleReply)(nil), "adf_add_ip_rule_reply_e8d4e804")
	api.RegisterMessage((*AdfAddL7Rule)(nil), "adf_add_l7_rule_45034242")
	api.RegisterMessage((*AdfAddL7RuleReply)(nil), "adf_add_l7_rule_reply_e8d4e804")
	api.RegisterMessage((*AdfApplicationDetails)(nil), "adf_application_details_0ef16c59")
	api.RegisterMessage((*AdfApplicationDump)(nil), "adf_application_dump_51077d14")
	api.RegisterMessage((*AdfCreateApplication)(nil), "adf_create_application_0ef16c59")
	api.RegisterMessage((*AdfCreateApplicationReply)(nil), "adf_create_application_reply_e8d4e804")
	api.RegisterMessage((*AdfCreateVersion)(nil), "adf_create_version_396ae46d")
	api.RegisterMessage((*AdfCreateVersionReply)(nil), "adf_create_version_reply_e8d4e804")
	api.RegisterMessage((*AdfDeleteApplication)(nil), "adf_delete_application_0cb71b0e")
	api.RegisterMessage((*AdfDeleteApplicationReply)(nil), "adf_delete_application_reply_e8d4e804")
	api.RegisterMessage((*AdfVersionCommit)(nil), "adf_version_commit_396ae46d")
	api.RegisterMessage((*AdfVersionCommitReply)(nil), "adf_version_commit_reply_e8d4e804")
	api.RegisterMessage((*AdfVersionDrop)(nil), "adf_version_drop_396ae46d")
	api.RegisterMessage((*AdfVersionDropReply)(nil), "adf_version_drop_reply_e8d4e804")
	api.RegisterMessage((*NetcapImsiDetails)(nil), "netcap_imsi_details_e002db45")
	api.RegisterMessage((*NetcapImsiDump)(nil), "netcap_imsi_dump_51077d14")
	api.RegisterMessage((*UpfGetNodeID)(nil), "upf_get_node_id_51077d14")
	api.RegisterMessage((*UpfGetNodeIDReply)(nil), "upf_get_node_id_reply_4f226741")
	api.RegisterMessage((*UpfImsiNetcapEnableDisable)(nil), "upf_imsi_netcap_enable_disable_4d8ef09f")
	api.RegisterMessage((*UpfImsiNetcapEnableDisableReply)(nil), "upf_imsi_netcap_enable_disable_reply_e8d4e804")
	api.RegisterMessage((*UpfNatPoolAdd)(nil), "upf_nat_pool_add_53c81402")
	api.RegisterMessage((*UpfNatPoolAddReply)(nil), "upf_nat_pool_add_reply_e8d4e804")
	api.RegisterMessage((*UpfNatPoolDetails)(nil), "upf_nat_pool_details_536a8c46")
	api.RegisterMessage((*UpfNatPoolDump)(nil), "upf_nat_pool_dump_51077d14")
	api.RegisterMessage((*UpfNwiAddDel)(nil), "upf_nwi_add_del_bc2ab757")
	api.RegisterMessage((*UpfNwiAddDelReply)(nil), "upf_nwi_add_del_reply_e8d4e804")
	api.RegisterMessage((*UpfNwiDetails)(nil), "upf_nwi_details_b845bcf1")
	api.RegisterMessage((*UpfNwiDump)(nil), "upf_nwi_dump_51077d14")
	api.RegisterMessage((*UpfPfcpEndpointAddDel)(nil), "upf_pfcp_endpoint_add_del_c10b6079")
	api.RegisterMessage((*UpfPfcpEndpointAddDelReply)(nil), "upf_pfcp_endpoint_add_del_reply_e8d4e804")
	api.RegisterMessage((*UpfPfcpEndpointDetails)(nil), "upf_pfcp_endpoint_details_84b7ba70")
	api.RegisterMessage((*UpfPfcpEndpointDump)(nil), "upf_pfcp_endpoint_dump_51077d14")
	api.RegisterMessage((*UpfPfcpFormat)(nil), "upf_pfcp_format_d522d6e1")
	api.RegisterMessage((*UpfPfcpFormatReply)(nil), "upf_pfcp_format_reply_8706f872")
	api.RegisterMessage((*UpfPfcpHeartbeatsGet)(nil), "upf_pfcp_heartbeats_get_51077d14")
	api.RegisterMessage((*UpfPfcpHeartbeatsGetReply)(nil), "upf_pfcp_heartbeats_get_reply_f5eafa3d")
	api.RegisterMessage((*UpfPfcpHeartbeatsSet)(nil), "upf_pfcp_heartbeats_set_f5eafa3d")
	api.RegisterMessage((*UpfPfcpHeartbeatsSetReply)(nil), "upf_pfcp_heartbeats_set_reply_e8d4e804")
	api.RegisterMessage((*UpfPfcpReencode)(nil), "upf_pfcp_reencode_d522d6e1")
	api.RegisterMessage((*UpfPfcpReencodeReply)(nil), "upf_pfcp_reencode_reply_68800422")
	api.RegisterMessage((*UpfPfcpServerSet)(nil), "upf_pfcp_server_set_747f398b")
	api.RegisterMessage((*UpfPfcpServerSetReply)(nil), "upf_pfcp_server_set_reply_e8d4e804")
	api.RegisterMessage((*UpfPfcpServerShow)(nil), "upf_pfcp_server_show_51077d14")
	api.RegisterMessage((*UpfPfcpServerShowReply)(nil), "upf_pfcp_server_show_reply_747f398b")
	api.RegisterMessage((*UpfPolicyAddDel)(nil), "upf_policy_add_del_111c586f")
	api.RegisterMessage((*UpfPolicyAddDelReply)(nil), "upf_policy_add_del_reply_e8d4e804")
	api.RegisterMessage((*UpfPolicyDetails)(nil), "upf_policy_details_1ee6f85d")
	api.RegisterMessage((*UpfPolicyDump)(nil), "upf_policy_dump_51077d14")
	api.RegisterMessage((*UpfSetNodeID)(nil), "upf_set_node_id_d2f43a0a")
	api.RegisterMessage((*UpfSetNodeIDReply)(nil), "upf_set_node_id_reply_e8d4e804")
	api.RegisterMessage((*UpfShowUeipExport)(nil), "upf_show_ueip_export_51077d14")
	api.RegisterMessage((*UpfShowUeipExportReply)(nil), "upf_show_ueip_export_reply_7aac337e")
	api.RegisterMessage((*UpfTdfUlEnableDisable)(nil), "upf_tdf_ul_enable_disable_53c1a78f")
	api.RegisterMessage((*UpfTdfUlEnableDisableReply)(nil), "upf_tdf_ul_enable_disable_reply_e8d4e804")
	api.RegisterMessage((*UpfTdfUlTable)(nil), "upf_tdf_ul_table_98d231ca")
	api.RegisterMessage((*UpfTdfUlTableAdd)(nil), "upf_tdf_ul_table_add_040a316b")
	api.RegisterMessage((*UpfTdfUlTableAddReply)(nil), "upf_tdf_ul_table_add_reply_e8d4e804")
	api.RegisterMessage((*UpfTdfUlTableReply)(nil), "upf_tdf_ul_table_reply_d1a9fc2e")
	api.RegisterMessage((*UpfUeipExportEnable)(nil), "upf_ueip_export_enable_77bf746e")
	api.RegisterMessage((*UpfUeipExportEnableReply)(nil), "upf_ueip_export_enable_reply_e8d4e804")
	api.RegisterMessage((*UpfUeipPoolDetails)(nil), "upf_ueip_pool_details_b4a36a1c")
	api.RegisterMessage((*UpfUeipPoolDump)(nil), "upf_ueip_pool_dump_51077d14")
	api.RegisterMessage((*UpfUeipPoolNwiAdd)(nil), "upf_ueip_pool_nwi_add_31b44993")
	api.RegisterMessage((*UpfUeipPoolNwiAddReply)(nil), "upf_ueip_pool_nwi_add_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*AdfActiveVersionDetails)(nil),
		(*AdfActiveVersionDump)(nil),
		(*AdfAddIPRule)(nil),
		(*AdfAddIPRuleReply)(nil),
		(*AdfAddL7Rule)(nil),
		(*AdfAddL7RuleReply)(nil),
		(*AdfApplicationDetails)(nil),
		(*AdfApplicationDump)(nil),
		(*AdfCreateApplication)(nil),
		(*AdfCreateApplicationReply)(nil),
		(*AdfCreateVersion)(nil),
		(*AdfCreateVersionReply)(nil),
		(*AdfDeleteApplication)(nil),
		(*AdfDeleteApplicationReply)(nil),
		(*AdfVersionCommit)(nil),
		(*AdfVersionCommitReply)(nil),
		(*AdfVersionDrop)(nil),
		(*AdfVersionDropReply)(nil),
		(*NetcapImsiDetails)(nil),
		(*NetcapImsiDump)(nil),
		(*UpfGetNodeID)(nil),
		(*UpfGetNodeIDReply)(nil),
		(*UpfImsiNetcapEnableDisable)(nil),
		(*UpfImsiNetcapEnableDisableReply)(nil),
		(*UpfNatPoolAdd)(nil),
		(*UpfNatPoolAddReply)(nil),
		(*UpfNatPoolDetails)(nil),
		(*UpfNatPoolDump)(nil),
		(*UpfNwiAddDel)(nil),
		(*UpfNwiAddDelReply)(nil),
		(*UpfNwiDetails)(nil),
		(*UpfNwiDump)(nil),
		(*UpfPfcpEndpointAddDel)(nil),
		(*UpfPfcpEndpointAddDelReply)(nil),
		(*UpfPfcpEndpointDetails)(nil),
		(*UpfPfcpEndpointDump)(nil),
		(*UpfPfcpFormat)(nil),
		(*UpfPfcpFormatReply)(nil),
		(*UpfPfcpHeartbeatsGet)(nil),
		(*UpfPfcpHeartbeatsGetReply)(nil),
		(*UpfPfcpHeartbeatsSet)(nil),
		(*UpfPfcpHeartbeatsSetReply)(nil),
		(*UpfPfcpReencode)(nil),
		(*UpfPfcpReencodeReply)(nil),
		(*UpfPfcpServerSet)(nil),
		(*UpfPfcpServerSetReply)(nil),
		(*UpfPfcpServerShow)(nil),
		(*UpfPfcpServerShowReply)(nil),
		(*UpfPolicyAddDel)(nil),
		(*UpfPolicyAddDelReply)(nil),
		(*UpfPolicyDetails)(nil),
		(*UpfPolicyDump)(nil),
		(*UpfSetNodeID)(nil),
		(*UpfSetNodeIDReply)(nil),
		(*UpfShowUeipExport)(nil),
		(*UpfShowUeipExportReply)(nil),
		(*UpfTdfUlEnableDisable)(nil),
		(*UpfTdfUlEnableDisableReply)(nil),
		(*UpfTdfUlTable)(nil),
		(*UpfTdfUlTableAdd)(nil),
		(*UpfTdfUlTableAddReply)(nil),
		(*UpfTdfUlTableReply)(nil),
		(*UpfUeipExportEnable)(nil),
		(*UpfUeipExportEnableReply)(nil),
		(*UpfUeipPoolDetails)(nil),
		(*UpfUeipPoolDump)(nil),
		(*UpfUeipPoolNwiAdd)(nil),
		(*UpfUeipPoolNwiAddReply)(nil),
	}
}
