// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package upf

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/travelping/upg-vpp/test/e2e/binapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service upf.
type RPCService interface {
	AdfActiveVersionDump(ctx context.Context, in *AdfActiveVersionDump) (RPCService_AdfActiveVersionDumpClient, error)
	AdfAddIPRule(ctx context.Context, in *AdfAddIPRule) (*AdfAddIPRuleReply, error)
	AdfAddL7Rule(ctx context.Context, in *AdfAddL7Rule) (*AdfAddL7RuleReply, error)
	AdfApplicationDump(ctx context.Context, in *AdfApplicationDump) (RPCService_AdfApplicationDumpClient, error)
	AdfCreateApplication(ctx context.Context, in *AdfCreateApplication) (*AdfCreateApplicationReply, error)
	AdfCreateVersion(ctx context.Context, in *AdfCreateVersion) (*AdfCreateVersionReply, error)
	AdfDeleteApplication(ctx context.Context, in *AdfDeleteApplication) (*AdfDeleteApplicationReply, error)
	AdfVersionCommit(ctx context.Context, in *AdfVersionCommit) (*AdfVersionCommitReply, error)
	AdfVersionDrop(ctx context.Context, in *AdfVersionDrop) (*AdfVersionDropReply, error)
	NetcapImsiDump(ctx context.Context, in *NetcapImsiDump) (RPCService_NetcapImsiDumpClient, error)
	UpfGetNodeID(ctx context.Context, in *UpfGetNodeID) (*UpfGetNodeIDReply, error)
	UpfImsiNetcapEnableDisable(ctx context.Context, in *UpfImsiNetcapEnableDisable) (*UpfImsiNetcapEnableDisableReply, error)
	UpfNatPoolAdd(ctx context.Context, in *UpfNatPoolAdd) (*UpfNatPoolAddReply, error)
	UpfNatPoolDump(ctx context.Context, in *UpfNatPoolDump) (RPCService_UpfNatPoolDumpClient, error)
	UpfNwiAddDel(ctx context.Context, in *UpfNwiAddDel) (*UpfNwiAddDelReply, error)
	UpfNwiDump(ctx context.Context, in *UpfNwiDump) (RPCService_UpfNwiDumpClient, error)
	UpfPfcpEndpointAddDel(ctx context.Context, in *UpfPfcpEndpointAddDel) (*UpfPfcpEndpointAddDelReply, error)
	UpfPfcpEndpointDump(ctx context.Context, in *UpfPfcpEndpointDump) (RPCService_UpfPfcpEndpointDumpClient, error)
	UpfPfcpFormat(ctx context.Context, in *UpfPfcpFormat) (*UpfPfcpFormatReply, error)
	UpfPfcpHeartbeatsGet(ctx context.Context, in *UpfPfcpHeartbeatsGet) (*UpfPfcpHeartbeatsGetReply, error)
	UpfPfcpHeartbeatsSet(ctx context.Context, in *UpfPfcpHeartbeatsSet) (*UpfPfcpHeartbeatsSetReply, error)
	UpfPfcpReencode(ctx context.Context, in *UpfPfcpReencode) (*UpfPfcpReencodeReply, error)
	UpfPfcpServerSet(ctx context.Context, in *UpfPfcpServerSet) (*UpfPfcpServerSetReply, error)
	UpfPfcpServerShow(ctx context.Context, in *UpfPfcpServerShow) (*UpfPfcpServerShowReply, error)
	UpfPolicyAddDel(ctx context.Context, in *UpfPolicyAddDel) (*UpfPolicyAddDelReply, error)
	UpfPolicyDump(ctx context.Context, in *UpfPolicyDump) (RPCService_UpfPolicyDumpClient, error)
	UpfSetNodeID(ctx context.Context, in *UpfSetNodeID) (*UpfSetNodeIDReply, error)
	UpfShowUeipExport(ctx context.Context, in *UpfShowUeipExport) (*UpfShowUeipExportReply, error)
	UpfTdfUlEnableDisable(ctx context.Context, in *UpfTdfUlEnableDisable) (*UpfTdfUlEnableDisableReply, error)
	UpfTdfUlTable(ctx context.Context, in *UpfTdfUlTable) (*UpfTdfUlTableReply, error)
	UpfTdfUlTableAdd(ctx context.Context, in *UpfTdfUlTableAdd) (*UpfTdfUlTableAddReply, error)
	UpfUeipExportEnable(ctx context.Context, in *UpfUeipExportEnable) (*UpfUeipExportEnableReply, error)
	UpfUeipPoolDump(ctx context.Context, in *UpfUeipPoolDump) (RPCService_UpfUeipPoolDumpClient, error)
	UpfUeipPoolNwiAdd(ctx context.Context, in *UpfUeipPoolNwiAdd) (*UpfUeipPoolNwiAddReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) AdfActiveVersionDump(ctx context.Context, in *AdfActiveVersionDump) (RPCService_AdfActiveVersionDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_AdfActiveVersionDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_AdfActiveVersionDumpClient interface {
	Recv() (*AdfActiveVersionDetails, error)
	api.Stream
}

type serviceClient_AdfActiveVersionDumpClient struct {
	api.Stream
}

func (c *serviceClient_AdfActiveVersionDumpClient) Recv() (*AdfActiveVersionDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *AdfActiveVersionDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) AdfAddIPRule(ctx context.Context, in *AdfAddIPRule) (*AdfAddIPRuleReply, error) {
	out := new(AdfAddIPRuleReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) AdfAddL7Rule(ctx context.Context, in *AdfAddL7Rule) (*AdfAddL7RuleReply, error) {
	out := new(AdfAddL7RuleReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) AdfApplicationDump(ctx context.Context, in *AdfApplicationDump) (RPCService_AdfApplicationDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_AdfApplicationDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_AdfApplicationDumpClient interface {
	Recv() (*AdfApplicationDetails, error)
	api.Stream
}

type serviceClient_AdfApplicationDumpClient struct {
	api.Stream
}

func (c *serviceClient_AdfApplicationDumpClient) Recv() (*AdfApplicationDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *AdfApplicationDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) AdfCreateApplication(ctx context.Context, in *AdfCreateApplication) (*AdfCreateApplicationReply, error) {
	out := new(AdfCreateApplicationReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) AdfCreateVersion(ctx context.Context, in *AdfCreateVersion) (*AdfCreateVersionReply, error) {
	out := new(AdfCreateVersionReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) AdfDeleteApplication(ctx context.Context, in *AdfDeleteApplication) (*AdfDeleteApplicationReply, error) {
	out := new(AdfDeleteApplicationReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) AdfVersionCommit(ctx context.Context, in *AdfVersionCommit) (*AdfVersionCommitReply, error) {
	out := new(AdfVersionCommitReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) AdfVersionDrop(ctx context.Context, in *AdfVersionDrop) (*AdfVersionDropReply, error) {
	out := new(AdfVersionDropReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) NetcapImsiDump(ctx context.Context, in *NetcapImsiDump) (RPCService_NetcapImsiDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_NetcapImsiDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_NetcapImsiDumpClient interface {
	Recv() (*NetcapImsiDetails, error)
	api.Stream
}

type serviceClient_NetcapImsiDumpClient struct {
	api.Stream
}

func (c *serviceClient_NetcapImsiDumpClient) Recv() (*NetcapImsiDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *NetcapImsiDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) UpfGetNodeID(ctx context.Context, in *UpfGetNodeID) (*UpfGetNodeIDReply, error) {
	out := new(UpfGetNodeIDReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfImsiNetcapEnableDisable(ctx context.Context, in *UpfImsiNetcapEnableDisable) (*UpfImsiNetcapEnableDisableReply, error) {
	out := new(UpfImsiNetcapEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfNatPoolAdd(ctx context.Context, in *UpfNatPoolAdd) (*UpfNatPoolAddReply, error) {
	out := new(UpfNatPoolAddReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfNatPoolDump(ctx context.Context, in *UpfNatPoolDump) (RPCService_UpfNatPoolDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_UpfNatPoolDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_UpfNatPoolDumpClient interface {
	Recv() (*UpfNatPoolDetails, error)
	api.Stream
}

type serviceClient_UpfNatPoolDumpClient struct {
	api.Stream
}

func (c *serviceClient_UpfNatPoolDumpClient) Recv() (*UpfNatPoolDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *UpfNatPoolDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) UpfNwiAddDel(ctx context.Context, in *UpfNwiAddDel) (*UpfNwiAddDelReply, error) {
	out := new(UpfNwiAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfNwiDump(ctx context.Context, in *UpfNwiDump) (RPCService_UpfNwiDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_UpfNwiDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_UpfNwiDumpClient interface {
	Recv() (*UpfNwiDetails, error)
	api.Stream
}

type serviceClient_UpfNwiDumpClient struct {
	api.Stream
}

func (c *serviceClient_UpfNwiDumpClient) Recv() (*UpfNwiDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *UpfNwiDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) UpfPfcpEndpointAddDel(ctx context.Context, in *UpfPfcpEndpointAddDel) (*UpfPfcpEndpointAddDelReply, error) {
	out := new(UpfPfcpEndpointAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfPfcpEndpointDump(ctx context.Context, in *UpfPfcpEndpointDump) (RPCService_UpfPfcpEndpointDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_UpfPfcpEndpointDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_UpfPfcpEndpointDumpClient interface {
	Recv() (*UpfPfcpEndpointDetails, error)
	api.Stream
}

type serviceClient_UpfPfcpEndpointDumpClient struct {
	api.Stream
}

func (c *serviceClient_UpfPfcpEndpointDumpClient) Recv() (*UpfPfcpEndpointDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *UpfPfcpEndpointDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) UpfPfcpFormat(ctx context.Context, in *UpfPfcpFormat) (*UpfPfcpFormatReply, error) {
	out := new(UpfPfcpFormatReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfPfcpHeartbeatsGet(ctx context.Context, in *UpfPfcpHeartbeatsGet) (*UpfPfcpHeartbeatsGetReply, error) {
	out := new(UpfPfcpHeartbeatsGetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpfPfcpHeartbeatsSet(ctx context.Context, in *UpfPfcpHeartbeatsSet) (*UpfPfcpHeartbeatsSetReply, error) {
	out := new(UpfPfcpHeartbeatsSetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfPfcpReencode(ctx context.Context, in *UpfPfcpReencode) (*UpfPfcpReencodeReply, error) {
	out := new(UpfPfcpReencodeReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfPfcpServerSet(ctx context.Context, in *UpfPfcpServerSet) (*UpfPfcpServerSetReply, error) {
	out := new(UpfPfcpServerSetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfPfcpServerShow(ctx context.Context, in *UpfPfcpServerShow) (*UpfPfcpServerShowReply, error) {
	out := new(UpfPfcpServerShowReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpfPolicyAddDel(ctx context.Context, in *UpfPolicyAddDel) (*UpfPolicyAddDelReply, error) {
	out := new(UpfPolicyAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfPolicyDump(ctx context.Context, in *UpfPolicyDump) (RPCService_UpfPolicyDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_UpfPolicyDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_UpfPolicyDumpClient interface {
	Recv() (*UpfPolicyDetails, error)
	api.Stream
}

type serviceClient_UpfPolicyDumpClient struct {
	api.Stream
}

func (c *serviceClient_UpfPolicyDumpClient) Recv() (*UpfPolicyDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *UpfPolicyDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) UpfSetNodeID(ctx context.Context, in *UpfSetNodeID) (*UpfSetNodeIDReply, error) {
	out := new(UpfSetNodeIDReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfShowUeipExport(ctx context.Context, in *UpfShowUeipExport) (*UpfShowUeipExportReply, error) {
	out := new(UpfShowUeipExportReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpfTdfUlEnableDisable(ctx context.Context, in *UpfTdfUlEnableDisable) (*UpfTdfUlEnableDisableReply, error) {
	out := new(UpfTdfUlEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfTdfUlTable(ctx context.Context, in *UpfTdfUlTable) (*UpfTdfUlTableReply, error) {
	out := new(UpfTdfUlTableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpfTdfUlTableAdd(ctx context.Context, in *UpfTdfUlTableAdd) (*UpfTdfUlTableAddReply, error) {
	out := new(UpfTdfUlTableAddReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfUeipExportEnable(ctx context.Context, in *UpfUeipExportEnable) (*UpfUeipExportEnableReply, error) {
	out := new(UpfUeipExportEnableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) UpfUeipPoolDump(ctx context.Context, in *UpfUeipPoolDump) (RPCService_UpfUeipPoolDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_UpfUeipPoolDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_UpfUeipPoolDumpClient interface {
	Recv() (*UpfUeipPoolDetails, error)
	api.Stream
}

type serviceClient_UpfUeipPoolDumpClient struct {
	api.Stream
}

func (c *serviceClient_UpfUeipPoolDumpClient) Recv() (*UpfUeipPoolDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *UpfUeipPoolDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) UpfUeipPoolNwiAdd(ctx context.Context, in *UpfUeipPoolNwiAdd) (*UpfUeipPoolNwiAddReply, error) {
	out := new(UpfUeipPoolNwiAddReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
