ARG BASE

FROM $BASE

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:longsleep/golang-backports && \
    apt-get update && \
    apt-get install -y golang-go iproute2 gdb curl tcpdump iputils-ping \
    libpcap-dev dumb-init git && \
    go get github.com/onsi/ginkgo/ginkgo && \
    mv /root/go/bin/ginkgo /usr/local/bin

ADD . /exttest

WORKDIR /exttest

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/bin/bash"]
