ARG BASE

FROM $BASE

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:longsleep/golang-backports && \
    apt-get update && \
    apt-get install -y golang-go iproute2 gdb curl tcpdump iputils-ping \
            libpcap-dev dumb-init

ADD . /exttest

WORKDIR /exttest

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/bin/bash"]
